"""discovery state

Revision ID: 052f924bbcb0
Revises: 48cd59cae5d7
Create Date: 2026-07-31 02:54:20.324465
"""
from alembic import op
import sqlalchemy as sa


revision = '052f924bbcb0'
down_revision = '48cd59cae5d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovery_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discovery_state'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discovery_state')
    # ### end Alembic commands ###
