"""round proposals

Revision ID: 05ce13fac69a
Revises: 0671edabe2ac
Create Date: 2026-08-13 21:42:52.539281
"""
import sqlalchemy as sa
from alembic import op

revision = "05ce13fac69a"
down_revision = "0671edabe2ac"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ADDS two tables and one column; touches no existing constraint, so it
    # does NOT need naming_convention=NAMING_CONVENTION -- that requirement
    # applies only to migrations calling drop_constraint against the legacy
    # tables, whose constraints are anonymous on the server and named in every
    # test DB. Same note as 0671edabe2ac, which this follows.
    #
    # Every timestamp is sa.DateTime(), not app.db.models.UTCDateTime(): the
    # autogenerated file renders the TypeDecorator by name and would need an
    # import of the application into a migration that must keep running after
    # the model moves. The on-disk type is identical -- UTCDateTime's impl IS
    # DateTime; the decorator only rejects naive values on the way in.
    op.create_table(
        "round_poll_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("last_run_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_round_poll_state")),
    )
    op.create_table(
        "round_proposals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("concert_id", sa.Integer(), nullable=False),
        sa.Column("dedupe_key", sa.String(length=400), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "lottery_round",
                "eligibility_item_sale",
                "stream_ticket_sale",
                "general_sale",
                "result_announcement",
                "payment_deadline",
                "fcfs_sale",
                "tour_package",
                "goods_sale",
                "upgrade",
                "other",
                name="roundkind",
            ),
            nullable=False,
        ),
        sa.Column("opens_at_utc", sa.DateTime(), nullable=True),
        sa.Column("closes_at_utc", sa.DateTime(), nullable=True),
        sa.Column("evidence_yaml", sa.Text(), server_default="", nullable=False),
        sa.Column("source_url", sa.String(length=1000), server_default="", nullable=False),
        sa.Column("first_seen_at", sa.DateTime(), nullable=False),
        sa.Column("dismissed_at", sa.DateTime(), nullable=True),
        sa.Column("applied_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["concert_id"],
            ["concerts.id"],
            name=op.f("fk_round_proposals_concert_id_concerts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_round_proposals")),
    )
    with op.batch_alter_table("round_proposals") as batch:
        batch.create_index(
            batch.f("ix_round_proposals_concert_id"), ["concert_id"], unique=False
        )
        # NAMED, and unique: this is what makes a re-poll UPDATE the row it
        # already has instead of adding a second one beside it every day -- and
        # SQLite's batch mode refuses an unnamed constraint outright.
        batch.create_index(
            "uq_round_proposal_key", ["concert_id", "dedupe_key"], unique=True
        )

    with op.batch_alter_table("concerts") as batch:
        # The POLL's stamp. Deliberately NOT a backfill of, or a rename of,
        # ladder_rechecked_at_utc: that column means "a human looked at this"
        # and orders /admin/quiet-ladders. NULL here means "never polled",
        # which on the day of deploy is the truth for every row.
        batch.add_column(sa.Column("ladder_polled_at_utc", sa.DateTime(), nullable=True))


def downgrade() -> None:
    with op.batch_alter_table("concerts") as batch:
        batch.drop_column("ladder_polled_at_utc")

    with op.batch_alter_table("round_proposals") as batch:
        batch.drop_index("uq_round_proposal_key")
        batch.drop_index(batch.f("ix_round_proposals_concert_id"))

    op.drop_table("round_proposals")
    op.drop_table("round_poll_state")
