"""pending drafts

Revision ID: 0a0f05ea8746
Revises: ed5c5bd28796
Create Date: 2026-08-02 10:22:00.157182
"""
from alembic import op
import sqlalchemy as sa


revision = '0a0f05ea8746'
down_revision = 'ed5c5bd28796'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_text', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('committed_at', sa.DateTime(), nullable=True),
    sa.Column('concert_id', sa.Integer(), nullable=True),
    sa.Column('discarded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['concert_id'], ['concerts.id'], name=op.f('fk_pending_drafts_concert_id_concerts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.discord_id'], name=op.f('fk_pending_drafts_created_by_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pending_drafts'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pending_drafts')
    # ### end Alembic commands ###
