"""user erasure set null fks

Make the three author FKs that point at users.discord_id nullable and
ondelete='SET NULL', so a user can actually be deleted (GDPR erasure).
Before this, PRAGMA foreign_keys=ON made deleting any user who ever created
a concert or a tag, or ever edited a concert, raise an FK violation.

SET NULL rather than CASCADE on purpose: these three columns point at
*shared community content*, and one person leaving must not delete the
catalogue everyone else follows. The author is anonymised instead.

Note on downgrade: it restores NOT NULL, so it will fail if any user has
actually been erased since the upgrade (those rows hold NULL and there is
no author to restore). That is deliberate -- inventing an author would be
worse than refusing.

Revision ID: 1384cadd692e
Revises: e8a1c9d2f7b5
Create Date: 2026-07-19 00:25:37.470501
"""
from alembic import op
import sqlalchemy as sa


revision = '1384cadd692e'
down_revision = 'e8a1c9d2f7b5'
branch_labels = None
depends_on = None

# The live database predates Base.metadata's NAMING_CONVENTION: `concerts` and
# `tags` carry a bare `FOREIGN KEY(created_by) REFERENCES users(discord_id)`
# with no name, and `tags` also has an unnamed `UNIQUE (name)`. A test DB built
# from metadata names all of those, so this divergence is invisible locally and
# only bites on the real server -- batch mode reflects the unnamed constraint,
# finds no `fk_concerts_created_by_users`, and aborts.
#
# Passing the convention into batch_alter_table lets Alembic assign these
# conventional names during reflection, so drop_constraint can address them.
# Keep this in sync with NAMING_CONVENTION in db/models.py.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concert_audit', schema=None,
                              naming_convention=NAMING_CONVENTION) as batch_op:
        batch_op.alter_column('edited_by',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_concert_audit_edited_by_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_concert_audit_edited_by_users'), 'users', ['edited_by'], ['discord_id'], ondelete='SET NULL')

    with op.batch_alter_table('concerts', schema=None,
                              naming_convention=NAMING_CONVENTION) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_concerts_created_by_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_concerts_created_by_users'), 'users', ['created_by'], ['discord_id'], ondelete='SET NULL')

    with op.batch_alter_table('tags', schema=None,
                              naming_convention=NAMING_CONVENTION) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_tags_created_by_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tags_created_by_users'), 'users', ['created_by'], ['discord_id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None,
                              naming_convention=NAMING_CONVENTION) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tags_created_by_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tags_created_by_users'), 'users', ['created_by'], ['discord_id'])
        batch_op.alter_column('created_by',
               existing_type=sa.BIGINT(),
               nullable=False)

    with op.batch_alter_table('concerts', schema=None,
                              naming_convention=NAMING_CONVENTION) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_concerts_created_by_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_concerts_created_by_users'), 'users', ['created_by'], ['discord_id'])
        batch_op.alter_column('created_by',
               existing_type=sa.BIGINT(),
               nullable=False)

    with op.batch_alter_table('concert_audit', schema=None,
                              naming_convention=NAMING_CONVENTION) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_concert_audit_edited_by_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_concert_audit_edited_by_users'), 'users', ['edited_by'], ['discord_id'])
        batch_op.alter_column('edited_by',
               existing_type=sa.BIGINT(),
               nullable=False)

    # ### end Alembic commands ###
