"""concert day cancelled

Revision ID: 1430ba5bbc7e
Revises: 84977144aad6
Create Date: 2026-07-17 23:41:56.920669
"""
from alembic import op
import sqlalchemy as sa


revision = '1430ba5bbc7e'
down_revision = '84977144aad6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concert_days', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancelled', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concert_days', schema=None) as batch_op:
        batch_op.drop_column('cancelled')

    # ### end Alembic commands ###
