"""hot path indices

Revision ID: 156863f03972
Revises: 61b32729019c
Create Date: 2026-07-17 19:04:24.159104
"""
from alembic import op

revision = '156863f03972'
down_revision = '61b32729019c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concert_days', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_concert_days_concert_id'), ['concert_id'], unique=False)

    with op.batch_alter_table('concert_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_concert_tags_tag_id'), ['tag_id'], unique=False)

    with op.batch_alter_table('reminder_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminder_rules_concert_id'), ['concert_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminder_rules_round_id'), ['round_id'], unique=False)

    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rounds_concert_id'), ['concert_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rounds_concert_id'))

    with op.batch_alter_table('reminder_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminder_rules_round_id'))
        batch_op.drop_index(batch_op.f('ix_reminder_rules_concert_id'))

    with op.batch_alter_table('concert_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concert_tags_tag_id'))

    with op.batch_alter_table('concert_days', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concert_days_concert_id'))

    # ### end Alembic commands ###
