"""tags

Revision ID: 2f2ad38de5d7
Revises: 7e3e104f55bc
Create Date: 2026-07-16 02:07:50.747258
"""
from alembic import op
import sqlalchemy as sa


revision = '2f2ad38de5d7'
down_revision = '7e3e104f55bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.Enum('franchise', 'artist', 'venue', 'group', name='tagkind'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.discord_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('concert_tags',
    sa.Column('concert_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concert_id'], ['concerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('concert_id', 'tag_id')
    )
    op.create_table('tag_members',
    sa.Column('group_tag_id', sa.Integer(), nullable=False),
    sa.Column('member_tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_tag_id', 'member_tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_members')
    op.drop_table('concert_tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
