"""draft completion

Revision ID: 2fa4d11a473a
Revises: ff500647fa9c
Create Date: 2026-08-05 20:53:21.026574
"""
from alembic import op
import sqlalchemy as sa


revision = '2fa4d11a473a'
down_revision = 'ff500647fa9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fetch_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('first_seen_url', sa.String(length=1000), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('declined_at', sa.DateTime(), nullable=True),
    sa.Column('decided_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['decided_by'], ['users.discord_id'], name=op.f('fk_fetch_domains_decided_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fetch_domains')),
    sa.UniqueConstraint('host', name=op.f('uq_fetch_domains_host'))
    )
    with op.batch_alter_table('pending_drafts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completion_yaml', sa.Text(), server_default='', nullable=False))

    with op.batch_alter_table('triage_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.String(length=20), server_default='classify', nullable=False))
        batch_op.add_column(sa.Column('drafts_completed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rounds_added', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rounds_rejected', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('blocked_domains', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('triage_runs', schema=None) as batch_op:
        batch_op.drop_column('blocked_domains')
        batch_op.drop_column('rounds_rejected')
        batch_op.drop_column('rounds_added')
        batch_op.drop_column('drafts_completed')
        batch_op.drop_column('kind')

    with op.batch_alter_table('pending_drafts', schema=None) as batch_op:
        batch_op.drop_column('completion_yaml')

    op.drop_table('fetch_domains')
    # ### end Alembic commands ###
