"""discovered events

Revision ID: 48cd59cae5d7
Revises: eb4cb4f7927a
Create Date: 2026-07-31 01:20:04.296777
"""
from alembic import op
import sqlalchemy as sa


revision = '48cd59cae5d7'
down_revision = 'eb4cb4f7927a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovered_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eventernote_event_id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('venue', sa.String(length=200), nullable=False),
    sa.Column('first_seen_via_tag_id', sa.Integer(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('announced_at', sa.DateTime(), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.Column('concert_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['concert_id'], ['concerts.id'], name=op.f('fk_discovered_events_concert_id_concerts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['first_seen_via_tag_id'], ['tags.id'], name=op.f('fk_discovered_events_first_seen_via_tag_id_tags'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discovered_events')),
    sa.UniqueConstraint('eventernote_event_id', name=op.f('uq_discovered_events_eventernote_event_id'))
    )
    with op.batch_alter_table('concert_days', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eventernote_event_id', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_concert_days_eventernote_event_id'), ['eventernote_event_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concert_days', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concert_days_eventernote_event_id'))
        batch_op.drop_column('eventernote_event_id')

    op.drop_table('discovered_events')
    # ### end Alembic commands ###
