"""round qualifiers association table

Revision ID: 4a47a347ad21
Revises: 08aa8b07ad1b
Create Date: 2026-07-19 23:02:37.349054

This is a brand-new table, so it is a plain CREATE TABLE. It does NOT need
the naming_convention=NAMING_CONVENTION batch/table-rebuild treatment that
the tags and user-erasure migrations use -- that dance is only for ALTERing
existing tables whose legacy constraints were created without names. The
constraint names here come straight from Base.metadata's NAMING_CONVENTION
at autogenerate time (see the op.f(...) names below).
"""
from alembic import op
import sqlalchemy as sa


revision = '4a47a347ad21'
down_revision = '08aa8b07ad1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('round_qualifiers',
    sa.Column('upgrade_round_id', sa.Integer(), nullable=False),
    sa.Column('qualifying_round_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['qualifying_round_id'], ['rounds.id'], name=op.f('fk_round_qualifiers_qualifying_round_id_rounds'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upgrade_round_id'], ['rounds.id'], name=op.f('fk_round_qualifiers_upgrade_round_id_rounds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('upgrade_round_id', 'qualifying_round_id', name=op.f('pk_round_qualifiers'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('round_qualifiers')
    # ### end Alembic commands ###
