"""add delivery_log

Revision ID: 4d208d277be7
Revises: 7deda13c049b
Create Date: 2026-07-28 04:18:36.760805
"""
from alembic import op
import sqlalchemy as sa


revision = '4d208d277be7'
down_revision = '7deda13c049b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_at_utc', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.Enum('reminder', 'notification', name='deliverysource'), nullable=False),
    sa.Column('outcome', sa.Enum('success', 'forbidden', 'transient_failure', name='deliveryoutcome'), nullable=False),
    sa.Column('anchor', sa.Enum('opens', 'closes', 'results', 'payment', 'event_start', name='anchor'), nullable=True),
    sa.Column('note_kind', sa.String(length=30), nullable=True),
    sa.Column('concert_title', sa.String(length=300), nullable=True),
    sa.Column('leg_label', sa.String(length=200), nullable=True),
    sa.Column('round_label', sa.String(length=200), nullable=True),
    sa.Column('concert_id', sa.Integer(), nullable=True),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.Column('day_id', sa.Integer(), nullable=True),
    sa.Column('sent_at_utc', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['concert_id'], ['concerts.id'], name=op.f('fk_delivery_log_concert_id_concerts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['day_id'], ['concert_days.id'], name=op.f('fk_delivery_log_day_id_concert_days'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], name=op.f('fk_delivery_log_round_id_rounds'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.discord_id'], name=op.f('fk_delivery_log_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delivery_log'))
    )
    with op.batch_alter_table('delivery_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_log_batch_at_utc'), ['batch_at_utc'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_log_batch_at_utc'))

    op.drop_table('delivery_log')
    # ### end Alembic commands ###
