"""user calendar token

Revision ID: 5238d67b86e0
Revises: 156863f03972
Create Date: 2026-07-17 19:59:35.666135
"""
from alembic import op
import sqlalchemy as sa


revision = '5238d67b86e0'
down_revision = '156863f03972'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calendar_token_hash', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_users_calendar_token_hash'), ['calendar_token_hash'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_calendar_token_hash'), type_='unique')
        batch_op.drop_column('calendar_token_hash')

    # ### end Alembic commands ###
