"""editor role flag

Revision ID: 54f9ca25125c
Revises: c680f2fbb288
Create Date: 2026-07-16 23:08:15.931251
"""
from alembic import op
import sqlalchemy as sa


revision = '54f9ca25125c'
down_revision = 'c680f2fbb288'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_editor', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_editor')

    # ### end Alembic commands ###
