"""initial schema

Revision ID: 5d294bd5d067
Revises: 
Create Date: 2026-07-15 03:40:54.485938
"""
from alembic import op
import sqlalchemy as sa


revision = '5d294bd5d067'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('discord_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('avatar_hash', sa.String(length=64), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('discord_id')
    )
    op.create_table('concerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('franchise', sa.String(length=100), nullable=True),
    sa.Column('venue', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.discord_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concert_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concert_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('starts_at_utc', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['concert_id'], ['concerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('windows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concert_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('lottery_round', 'eligibility_item_sale', 'stream_ticket_sale', 'general_sale', 'result_announcement', 'payment_deadline', 'other', name='windowkind'), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('opens_at_utc', sa.DateTime(), nullable=True),
    sa.Column('closes_at_utc', sa.DateTime(), nullable=True),
    sa.Column('applies_to', sa.JSON(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['concert_id'], ['concerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reminder_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('concert_id', sa.Integer(), nullable=True),
    sa.Column('window_id', sa.Integer(), nullable=True),
    sa.Column('anchor', sa.Enum('opens', 'closes', 'event_start', name='anchor'), nullable=False),
    sa.Column('offset_days', sa.Integer(), nullable=False),
    sa.Column('offset_hours', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('dm', 'channel', name='channel'), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['concert_id'], ['concerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.discord_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['window_id'], ['windows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reminder_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('window_id', sa.Integer(), nullable=True),
    sa.Column('day_id', sa.Integer(), nullable=True),
    sa.Column('anchor', sa.Enum('opens', 'closes', 'event_start', name='anchor'), nullable=False),
    sa.Column('fire_at_utc', sa.DateTime(), nullable=False),
    sa.Column('sent_at_utc', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['concert_days.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['reminder_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['window_id'], ['windows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reminder_queue', schema=None) as batch_op:
        batch_op.create_index('ix_reminder_queue_due', ['sent_at_utc', 'fire_at_utc'], unique=False)

    # Functional dedupe index — hand-written because autogenerate can't reflect
    # expression indexes on SQLite. NULL window/day coalesce to 0 so re-planning
    # a rule upserts instead of duplicating (plain UNIQUE treats NULLs as distinct).
    op.execute(
        "CREATE UNIQUE INDEX uq_reminder_queue_dedupe ON reminder_queue "
        "(rule_id, coalesce(window_id, 0), coalesce(day_id, 0), anchor)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS uq_reminder_queue_dedupe")
    with op.batch_alter_table('reminder_queue', schema=None) as batch_op:
        batch_op.drop_index('ix_reminder_queue_due')

    op.drop_table('reminder_queue')
    op.drop_table('reminder_rules')
    op.drop_table('windows')
    op.drop_table('concert_days')
    op.drop_table('concerts')
    op.drop_table('users')
    # ### end Alembic commands ###
