"""dm blocked since

Revision ID: 5ea945b713c4
Revises: 1430ba5bbc7e
Create Date: 2026-07-18 10:51:21.222016
"""
from alembic import op
import sqlalchemy as sa


revision = '5ea945b713c4'
down_revision = '1430ba5bbc7e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dm_blocked_since', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('dm_blocked_since')

    # ### end Alembic commands ###
