"""concert event id

Revision ID: 61b32729019c
Revises: 96e348a6310c
Create Date: 2026-07-17 02:49:03.072838
"""
from alembic import op
import sqlalchemy as sa


revision = '61b32729019c'
down_revision = '96e348a6310c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Add nullable first, backfill existing rows to their current numeric id
    # (so old /concerts/<id> links keep resolving), THEN constrain -- adding
    # a NOT NULL+UNIQUE column directly would fail against existing rows.
    with op.batch_alter_table('concerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.String(length=100), nullable=True))

    op.execute("UPDATE concerts SET event_id = CAST(id AS TEXT)")

    with op.batch_alter_table('concerts', schema=None) as batch_op:
        batch_op.alter_column('event_id', nullable=False)
        batch_op.create_unique_constraint(batch_op.f('uq_concerts_event_id'), ['event_id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concerts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_concerts_event_id'), type_='unique')
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###
