"""round_outcome_days

Revision ID: 7deda13c049b
Revises: ce43bfcfcae3
Create Date: 2026-07-26 21:26:27.006993
"""
from alembic import op
import sqlalchemy as sa


revision = '7deda13c049b'
down_revision = 'ce43bfcfcae3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('round_outcome_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.Enum('won', 'lost', name='legresult'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['concert_days.id'], name=op.f('fk_round_outcome_days_day_id_concert_days'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], name=op.f('fk_round_outcome_days_round_id_rounds'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.discord_id'], name=op.f('fk_round_outcome_days_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_round_outcome_days'))
    )
    with op.batch_alter_table('round_outcome_days', schema=None) as batch_op:
        batch_op.create_index('uq_round_outcome_day', ['user_id', 'round_id', 'day_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('round_outcome_days', schema=None) as batch_op:
        batch_op.drop_index('uq_round_outcome_day')

    op.drop_table('round_outcome_days')
    # ### end Alembic commands ###
