"""concert audit log

Revision ID: 84977144aad6
Revises: 5238d67b86e0
Create Date: 2026-07-17 20:31:25.847661
"""
from alembic import op
import sqlalchemy as sa


revision = '84977144aad6'
down_revision = '5238d67b86e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concert_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concert_id', sa.Integer(), nullable=False),
    sa.Column('edited_by', sa.BigInteger(), nullable=False),
    sa.Column('edited_at_utc', sa.DateTime(), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['concert_id'], ['concerts.id'], name=op.f('fk_concert_audit_concert_id_concerts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['edited_by'], ['users.discord_id'], name=op.f('fk_concert_audit_edited_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_concert_audit'))
    )
    with op.batch_alter_table('concert_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_concert_audit_concert_id'), ['concert_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concert_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concert_audit_concert_id'))

    op.drop_table('concert_audit')
    # ### end Alembic commands ###
