"""presets subscriptions notifications

Revision ID: 8874c0b2ba2d
Revises: 2f2ad38de5d7
Create Date: 2026-07-16 02:14:39.997677
"""
from alembic import op
import sqlalchemy as sa


revision = '8874c0b2ba2d'
down_revision = '2f2ad38de5d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at_utc', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.discord_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reminder_presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.discord_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preset_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preset_id', sa.Integer(), nullable=False),
    sa.Column('anchor', sa.Enum('opens', 'closes', 'event_start', name='anchor'), nullable=False),
    sa.Column('offset_days', sa.Integer(), nullable=False),
    sa.Column('offset_hours', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['preset_id'], ['reminder_presets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('preset_id', sa.Integer(), nullable=True),
    sa.Column('notify', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['preset_id'], ['reminder_presets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.discord_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tag_subscriptions', schema=None) as batch_op:
        batch_op.create_index('uq_tag_sub', ['user_id', 'tag_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag_subscriptions', schema=None) as batch_op:
        batch_op.drop_index('uq_tag_sub')

    op.drop_table('tag_subscriptions')
    op.drop_table('preset_items')
    op.drop_table('reminder_presets')
    op.drop_table('notifications')
    # ### end Alembic commands ###
