"""venue tag region and location url

Revision ID: 96e348a6310c
Revises: df44c9169cc7
Create Date: 2026-07-17 02:17:12.894699
"""
from alembic import op
import sqlalchemy as sa


revision = '96e348a6310c'
down_revision = 'df44c9169cc7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('region', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_column('region')
        batch_op.drop_column('location_url')

    # ### end Alembic commands ###
