"""concert kind

Revision ID: 9e9f75b2c10a
Revises: 20b27b1046f4
Create Date: 2026-07-17 01:33:04.191805
"""
from alembic import op
import sqlalchemy as sa


revision = '9e9f75b2c10a'
down_revision = '20b27b1046f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.Enum('concert', 'tour', 'festival', 'release', 'meet_greet', 'fan_meeting', 'talk', 'stage', 'screening', 'goods', 'stream', 'other', name='concertkind'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concerts', schema=None) as batch_op:
        batch_op.drop_column('kind')

    # ### end Alembic commands ###
