"""character tags

Revision ID: bb9780f0ad82
Revises: 34179560cec0
Create Date: 2026-08-01 00:45:24.643510
"""
from alembic import op
import sqlalchemy as sa


revision = 'bb9780f0ad82'
down_revision = '34179560cec0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voiced_by_tag_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_tags_voiced_by_tag_id_tags'), 'tags', ['voiced_by_tag_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # drop_constraint removed (project rule: SQLite runs migrations in batch
    # mode and the live DB's older tables carry anonymous constraints that a
    # metadata-built test DB never reflects, so drop_constraint passes locally
    # and can die on the server -- see CLAUDE.md's Migrations section). Batch
    # mode's drop_column alone recreates the table without both the column
    # and any constraint that references it, so no separate drop is needed.
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_column('voiced_by_tag_id')

    # ### end Alembic commands ###
