"""default preset and structured notifications

Revision ID: c680f2fbb288
Revises: 901e562f80dd
Create Date: 2026-07-16 14:25:38.578939
"""
from alembic import op
import sqlalchemy as sa


revision = 'c680f2fbb288'
down_revision = '901e562f80dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('concert_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('kind', sa.String(length=30), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_notifications_concert_id_concerts'), 'concerts', ['concert_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('reminder_presets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder_presets', schema=None) as batch_op:
        batch_op.drop_column('is_default')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_notifications_concert_id_concerts'), type_='foreignkey')
        batch_op.drop_column('kind')
        batch_op.drop_column('concert_id')

    # ### end Alembic commands ###
