"""concert subscriptions

Two brand-new tables (concert_subscriptions, leg_opt_outs), so these are
plain CREATE TABLEs. Unlike 1384cadd692e, this migration needs NO legacy
naming_convention fixture in its batch_alter_table calls: that treatment
only matters when ALTERing an existing table whose original constraints
were created unnamed. New tables get named constraints from Base's
NAMING_CONVENTION at CREATE time, so nothing here rebuilds an old table.
No backfill either -- absence of a row means "follow the tag default",
which is exactly the pre-branch behaviour, so every existing board keeps
working with these tables empty.

Revision ID: cc82d6500300
Revises: ce1a80bb66f4
Create Date: 2026-07-19 21:25:18.445085
"""
from alembic import op
import sqlalchemy as sa


revision = 'cc82d6500300'
down_revision = 'ce1a80bb66f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concert_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('concert_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('subscribed', 'opted_out', name='subscriptionstate'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['concert_id'], ['concerts.id'], name=op.f('fk_concert_subscriptions_concert_id_concerts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.discord_id'], name=op.f('fk_concert_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_concert_subscriptions'))
    )
    with op.batch_alter_table('concert_subscriptions', schema=None) as batch_op:
        batch_op.create_index('uq_concert_subscription', ['user_id', 'concert_id'], unique=True)

    op.create_table('leg_opt_outs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('concert_day_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['concert_day_id'], ['concert_days.id'], name=op.f('fk_leg_opt_outs_concert_day_id_concert_days'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.discord_id'], name=op.f('fk_leg_opt_outs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leg_opt_outs'))
    )
    with op.batch_alter_table('leg_opt_outs', schema=None) as batch_op:
        batch_op.create_index('uq_leg_opt_out', ['user_id', 'concert_day_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leg_opt_outs', schema=None) as batch_op:
        batch_op.drop_index('uq_leg_opt_out')

    op.drop_table('leg_opt_outs')
    with op.batch_alter_table('concert_subscriptions', schema=None) as batch_op:
        batch_op.drop_index('uq_concert_subscription')

    op.drop_table('concert_subscriptions')
    # ### end Alembic commands ###
