"""round outcomes

Revision ID: d4cfaf0149ee
Revises: 5ea945b713c4
Create Date: 2026-07-18 13:28:17.886283
"""
from alembic import op
import sqlalchemy as sa


revision = 'd4cfaf0149ee'
down_revision = '5ea945b713c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('round_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.Enum('not_applied', 'applied', 'won', 'lost', 'paid', name='lotteryoutcome'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], name=op.f('fk_round_outcomes_round_id_rounds'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.discord_id'], name=op.f('fk_round_outcomes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_round_outcomes'))
    )
    with op.batch_alter_table('round_outcomes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_round_outcome'), ['user_id', 'round_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('round_outcomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_round_outcome'))

    op.drop_table('round_outcomes')
    # ### end Alembic commands ###
