"""discovery sweep counts

How the last Eventernote sweep went, so /admin/discoveries can tell a broken
sweep from a quiet one. Both columns are nullable and NULL means UNKNOWN, not
zero -- every existing row predates any recorded sweep, and a sweep that dies
is re-stamped with no counts at all.

Additive only, so the normal deploy order applies (upgrade, then restart).

Revision ID: d4dac7d14230
Revises: 052f924bbcb0
Create Date: 2026-07-31 05:37:04.259216
"""
from alembic import op
import sqlalchemy as sa


revision = 'd4dac7d14230'
down_revision = '052f924bbcb0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discovery_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_fetched', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_failed', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discovery_state', schema=None) as batch_op:
        batch_op.drop_column('last_failed')
        batch_op.drop_column('last_fetched')

    # ### end Alembic commands ###
