"""discovery sweep counts

How the last Eventernote sweep went, so /admin/discoveries can tell a broken
sweep from a quiet one, plus where the next one resumes.

last_fetched/last_failed/last_truncated are nullable and NULL means UNKNOWN,
not zero/false -- every existing row predates any recorded sweep, and a sweep
that dies is re-stamped with no report at all.

sweep_cursor_tag_id is the tags.id the NEXT sweep starts from. Deliberately a
plain Integer and NOT a foreign key: it is a position in an ordering, not a
reference to a row, and a deleted tag must leave it as a harmless "start at or
after this id" rather than trip a constraint or get SET NULL'd back to the
beginning of the list.

Additive only, so the normal deploy order applies (upgrade, then restart).

Revision ID: d4dac7d14230
Revises: 052f924bbcb0
Create Date: 2026-07-31 05:37:04.259216
"""
from alembic import op
import sqlalchemy as sa


revision = 'd4dac7d14230'
down_revision = '052f924bbcb0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discovery_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_fetched', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_failed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_truncated', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sweep_cursor_tag_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discovery_state', schema=None) as batch_op:
        batch_op.drop_column('sweep_cursor_tag_id')
        batch_op.drop_column('last_truncated')
        batch_op.drop_column('last_failed')
        batch_op.drop_column('last_fetched')

    # ### end Alembic commands ###
