"""api token hash

Revision ID: dd8f33a8747c
Revises: 2fa4d11a473a
Create Date: 2026-08-08 02:37:26.262785
"""
from alembic import op
import sqlalchemy as sa


revision = 'dd8f33a8747c'
down_revision = '2fa4d11a473a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_token_hash', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_users_api_token_hash'), ['api_token_hash'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_api_token_hash'), type_='unique')
        batch_op.drop_column('api_token_hash')

    # ### end Alembic commands ###
