"""rich event fields

Revision ID: df44c9169cc7
Revises: 9e9f75b2c10a
Create Date: 2026-07-17 01:51:26.232915
"""
from alembic import op
import sqlalchemy as sa


revision = 'df44c9169cc7'
down_revision = '9e9f75b2c10a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concert_days', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('venue', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('venue_address', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('doors_at_utc', sa.DateTime(), nullable=True))

    with op.batch_alter_table('concerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_en', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('organizer', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('categories', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('eventernote_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('official_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('source_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('performers_text', sa.Text(), nullable=True))

    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label_en', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('label_en')

    with op.batch_alter_table('concerts', schema=None) as batch_op:
        batch_op.drop_column('performers_text')
        batch_op.drop_column('source_url')
        batch_op.drop_column('official_url')
        batch_op.drop_column('eventernote_url')
        batch_op.drop_column('categories')
        batch_op.drop_column('organizer')
        batch_op.drop_column('title_en')

    with op.batch_alter_table('concert_days', schema=None) as batch_op:
        batch_op.drop_column('doors_at_utc')
        batch_op.drop_column('venue_address')
        batch_op.drop_column('venue')
        batch_op.drop_column('city')

    # ### end Alembic commands ###
