"""dismissal reason

Revision ID: ed5c5bd28796
Revises: bb9780f0ad82
Create Date: 2026-08-01 22:56:49.180837
"""
from alembic import op
import sqlalchemy as sa


revision = 'ed5c5bd28796'
down_revision = 'bb9780f0ad82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discovered_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dismiss_reason', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discovered_events', schema=None) as batch_op:
        batch_op.drop_column('dismiss_reason')

    # ### end Alembic commands ###
