"""add users.language

Revision ID: f5e514a2daac
Revises: 4a47a347ad21
Create Date: 2026-07-20 18:48:27.260262
"""
from alembic import op
import sqlalchemy as sa


revision = 'f5e514a2daac'
down_revision = '4a47a347ad21'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=8), server_default='en', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
