"""round required item

Revision ID: f846bca262ad
Revises: 0a0f05ea8746
Create Date: 2026-08-02 16:24:08.021989
"""
from alembic import op
import sqlalchemy as sa


revision = 'f846bca262ad'
down_revision = '0a0f05ea8746'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_item_round_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_rounds_required_item_round_id'), ['required_item_round_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_rounds_required_item_round_id_rounds'), 'rounds', ['required_item_round_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # drop_constraint removed (project rule: SQLite runs migrations in batch
    # mode and the live DB's older tables carry anonymous constraints that a
    # metadata-built test DB never reflects, so drop_constraint passes locally
    # and can die on the server -- see CLAUDE.md's Migrations section). Batch
    # mode's drop_column alone recreates the table without the column and
    # without any constraint that references it (the FK needs no separate
    # drop), exactly as bb9780f0ad82's downgrade does for voiced_by_tag_id.
    #
    # drop_index is DIFFERENT and stays, unlike drop_constraint: this index
    # was minted by THIS migration's own create_index(batch_op.f(...)) above,
    # not inherited from a pre-naming-convention legacy table, so its name is
    # exact and unambiguous -- no anonymous-constraint guessing involved.
    # Confirmed by reproducing the round-trip: batch mode's recreate step
    # reflects the table's existing indexes and reapplies them verbatim
    # post-rebuild; without an explicit drop_index it tried to recreate
    # ix_rounds_required_item_round_id against a table that no longer has the
    # column, raising "no such column: required_item_round_id".
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rounds_required_item_round_id'))
        batch_op.drop_column('required_item_round_id')

    # ### end Alembic commands ###
