"""proposal carries a whole round

Revision ID: fc4a98ad678a
Revises: 05ce13fac69a
Create Date: 2026-08-14 08:46:01.208788
"""
from alembic import op
import sqlalchemy as sa


revision = 'fc4a98ad678a'
down_revision = '05ce13fac69a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('round_proposals', schema=None) as batch_op:
        # `sa.DateTime()`, hand-substituted for the autogenerated
        # `app.db.models.UTCDateTime()`: the TypeDecorator is an app-level
        # gatekeeper (it refuses naive datetimes on write), the column
        # underneath it is a plain DATETIME, and the generated name is not even
        # bound in this module -- Alembic emits no `import app.db.models`, so
        # the revision does not run until this substitution is made.
        batch_op.add_column(sa.Column('results_at_utc', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('payment_deadline_at_utc', sa.DateTime(), nullable=True))
        # NOT NULL with a server-side '[]': every proposal recorded before this
        # migration named no legs, and "no legs named" already means "every
        # leg". A nullable column would give that one convention a second
        # spelling, which every reader downstream would then have to branch on.
        batch_op.add_column(sa.Column('applies_to_labels', sa.JSON(), server_default='[]', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('round_proposals', schema=None) as batch_op:
        batch_op.drop_column('applies_to_labels')
        batch_op.drop_column('payment_deadline_at_utc')
        batch_op.drop_column('results_at_utc')

    # ### end Alembic commands ###
