"""triage runs

Revision ID: ff500647fa9c
Revises: db750444962a
Create Date: 2026-08-05 13:55:00.050587
"""
from alembic import op
import sqlalchemy as sa


revision = 'ff500647fa9c'
down_revision = 'db750444962a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('triage_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_by', sa.BigInteger(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('prune_yaml', sa.Text(), nullable=False),
    sa.Column('leads_seen', sa.Integer(), nullable=True),
    sa.Column('productions', sa.Integer(), nullable=True),
    sa.Column('dismissals_proposed', sa.Integer(), nullable=True),
    sa.Column('drafts_created', sa.Integer(), nullable=True),
    sa.Column('skipped', sa.Integer(), nullable=True),
    sa.Column('calendar_skipped', sa.Integer(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['requested_by'], ['users.discord_id'], name=op.f('fk_triage_runs_requested_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_triage_runs'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('triage_runs')
    # ### end Alembic commands ###
