"""Database schema (SQLAlchemy 2.0 typed style).

Design recap (see README):
  concerts ─┬─ concert_days      "Day 1", 昼公演/夜公演 — actual show datetimes
            └─ rounds            generic typed deadline rounds (lotteries, sales...)
  users ──── reminder_rules      "remind me N days before/after X"
  reminder_queue                 materialized outbox the scheduler drains

Timezone rule enforced HERE, at the boundary: the UTCDateTime type refuses
naive datetimes on write and always returns aware-UTC on read. SQLite itself
has no timezone concept, so we make the ORM the gatekeeper.
"""

from datetime import UTC, datetime

from sqlalchemy import (
    JSON,
    BigInteger,
    Boolean,
    DateTime,
    Enum,
    ForeignKey,
    Index,
    MetaData,
    String,
    Text,
    TypeDecorator,
    text,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship

from app.domain.slugs import tag_slug_base
from app.domain.types import (
    Anchor,
    BroadcastMode,
    Channel,
    ConcertKind,
    DeliveryOutcome,
    DeliverySource,
    LegResult,
    LotteryOutcome,
    RoundKind,
    SubscriptionState,
    TagKind,
)


class UTCDateTime(TypeDecorator):
    """Store aware-UTC datetimes in SQLite; reject naive ones loudly."""

    impl = DateTime
    cache_ok = True

    def process_bind_param(self, value: datetime | None, dialect):
        if value is None:
            return None
        if value.tzinfo is None:
            raise ValueError("naive datetime rejected — store timezone-aware UTC only")
        return value.astimezone(UTC).replace(tzinfo=None)  # normalized, stored naive

    def process_result_value(self, value: datetime | None, dialect):
        return value.replace(tzinfo=UTC) if value is not None else None


# Every constraint gets a deterministic name. SQLite migrations run in
# batch (table-rebuild) mode, which refuses unnamed constraints - this
# convention makes autogenerated migrations safe by construction.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


def _now() -> datetime:
    return datetime.now(UTC)


class User(Base):
    __tablename__ = "users"

    discord_id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=False)
    username: Mapped[str] = mapped_column(String(100))
    avatar_hash: Mapped[str | None] = mapped_column(String(64))
    timezone: Mapped[str] = mapped_column(String(64), default="America/Moncton")
    # tz_auto: timezone is browser-detected until the user overrides it manually
    tz_auto: Mapped[bool] = mapped_column(default=True, server_default="1")
    # UI + DM language. "en" is the source language; the lang cookie is a
    # per-browser cache of this column (synced at login and on change) so the
    # web middleware never needs a DB read. Discord always reads this column.
    language: Mapped[str] = mapped_column(String(8), default="en", server_default="en")
    # DB-persisted editor grant, toggled by admins (web/Discord). Final editor
    # status is this OR settings.editor_whitelist OR settings.admin_whitelist.
    is_editor: Mapped[bool] = mapped_column(default=False, server_default="0")
    # Personal calendar-feed subscription token, hashed at rest (same pattern
    # as WebSession.token_hash) -- the raw token lives only in the feed URL,
    # shown once at generation time, never stored or re-displayable.
    calendar_token_hash: Mapped[str | None] = mapped_column(String(64), unique=True)
    # None = DMs working (or never tested); a timestamp = the most recent
    # attempted send hit discord.Forbidden. One shared signal across both
    # reminder-DM and notification-DM sends (see scheduler/loop.py's
    # DeliveryOutcome and db/service.py's record_dm_outcome). Surfaced as a
    # sitewide banner via auth.SessionUser.dm_blocked.
    dm_blocked_since: Mapped[datetime | None] = mapped_column(UTCDateTime)
    # First-run guided setup: 0-4 = the wizard step in progress, >=5 = done
    # (finished naturally or skipped). Offered once at first login only --
    # never re-derived from this value on any later login.
    onboarding_step: Mapped[int] = mapped_column(default=0, server_default="0")
    created_at: Mapped[datetime] = mapped_column(UTCDateTime, default=_now)

    # passive_deletes: reminder_rules.user_id is NOT NULL with ondelete=CASCADE,
    # so let the DB delete the children. Without this the ORM tries to UPDATE
    # them to user_id=NULL first and deleting a user fails (see delete_user).
    rules: Mapped[list["ReminderRule"]] = relationship(
        back_populates="user", passive_deletes=True
    )


class WebSession(Base):
    """Server-side login sessions: revocable, expiring, replay-proof.

    The cookie carries an opaque random token; only its SHA-256 lands here,
    so a leaked database cannot be turned back into usable cookies.
    Logout revokes the row -> a replayed cookie is dead server-side.
    """

    __tablename__ = "web_sessions"

    id: Mapped[int] = mapped_column(primary_key=True)
    token_hash: Mapped[str] = mapped_column(String(64), unique=True)
    user_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("users.discord_id", ondelete="CASCADE")
    )
    created_at: Mapped[datetime] = mapped_column(UTCDateTime, default=_now)
    expires_at: Mapped[datetime] = mapped_column(UTCDateTime)
    revoked_at: Mapped[datetime | None] = mapped_column(UTCDateTime)


class Concert(Base):
    __tablename__ = "concerts"

    id: Mapped[int] = mapped_column(primary_key=True)
    # URL-facing handle, distinct from the internal PK (which every FK still
    # targets). Editor-chosen at creation; existing concerts were backfilled
    # to str(id) so old links keep resolving.
    event_id: Mapped[str] = mapped_column(String(100), unique=True)
    title: Mapped[str] = mapped_column(String(200))
    # Viewer-locale variants of the user-entered title (en/zh); ja IS the
    # original. All UGC-translation columns are nullable with no backfill --
    # loc_field falls back to the original when a variant is empty.
    title_en: Mapped[str | None] = mapped_column(String(200))
    title_zh: Mapped[str | None] = mapped_column(String(200))
    kind: Mapped[ConcertKind | None] = mapped_column(
        Enum(ConcertKind, values_callable=lambda e: [m.value for m in e])
    )
    organizer: Mapped[str | None] = mapped_column(String(200))  # free-text artist/organizer
    categories: Mapped[str | None] = mapped_column(String(300))  # comma-sep free text
    eventernote_url: Mapped[str | None] = mapped_column(String(500))
    official_url: Mapped[str | None] = mapped_column(String(500))
    source_url: Mapped[str | None] = mapped_column(String(500))
    performers_text: Mapped[str | None] = mapped_column(Text)  # free-text, one per line
    franchise: Mapped[str | None] = mapped_column(String(100))  # "Hasunosora", "Gakumas"...
    notes: Mapped[str | None] = mapped_column(Text)
    notes_en: Mapped[str | None] = mapped_column(Text)
    notes_zh: Mapped[str | None] = mapped_column(Text)
    # SET NULL, not CASCADE: erasing the editor who filed a concert must not
    # delete the shared catalogue entry everyone else follows. NULL = the
    # author was deleted (GDPR erasure) -- see service.delete_user.
    created_by: Mapped[int | None] = mapped_column(
        BigInteger, ForeignKey("users.discord_id", ondelete="SET NULL")
    )
    created_at: Mapped[datetime] = mapped_column(UTCDateTime, default=_now)

    creator: Mapped["User | None"] = relationship()  # also fixes ORM insert ordering
    days: Mapped[list["ConcertDay"]] = relationship(
        back_populates="concert", cascade="all, delete-orphan", order_by="ConcertDay.starts_at_utc"
    )
    rounds: Mapped[list["Round"]] = relationship(
        back_populates="concert", cascade="all, delete-orphan"
    )
    tags: Mapped[list["Tag"]] = relationship(secondary="concert_tags", order_by="Tag.name")
    audits: Mapped[list["ConcertAudit"]] = relationship(
        cascade="all, delete-orphan", order_by="ConcertAudit.edited_at_utc.desc()"
    )


class ConcertAudit(Base):
    """One row per edit that actually changed a tracked scalar field --
    lightweight by design: only the concert's own top-level fields (title,
    organizer, URLs, notes, ...), not day/round/tag adds-and-removes. `changes`
    is a JSON list of {"field", "before", "after"}; enum values are stored as
    their plain `.value` string so the column stays JSON-serializable."""

    __tablename__ = "concert_audit"

    id: Mapped[int] = mapped_column(primary_key=True)
    concert_id: Mapped[int] = mapped_column(
        ForeignKey("concerts.id", ondelete="CASCADE"), index=True
    )
    # SET NULL on erasure (see Concert.created_by): the edit itself stays in
    # the history, its author anonymised.
    edited_by: Mapped[int | None] = mapped_column(
        BigInteger, ForeignKey("users.discord_id", ondelete="SET NULL")
    )
    edited_at_utc: Mapped[datetime] = mapped_column(UTCDateTime, default=_now)
    changes: Mapped[list] = mapped_column(JSON)

    editor: Mapped["User | None"] = relationship()


def _derive_tag_slug(context) -> str:
    """INSERT-time default for `Tag.slug`, so a handle is never absent.

    Guarantees NON-NULLNESS only. `service.assign_tag_slug` is still the single
    path that guarantees a non-COLLIDING handle -- it de-duplicates against the
    DB and the pending session, which a column default cannot do (it has no
    session and cannot query). Every production create path calls it, so this
    default does not fire there at all; it exists so that constructing a `Tag`
    without one is not a NOT NULL crash, in tests and in any future caller.

    Two same-derived handles reaching the DB raise IntegrityError, which is the
    correct outcome: loud, at the boundary, rather than a silent duplicate
    identity.
    """
    params = context.get_current_parameters()
    kind = params.get("kind")
    fallback = kind.value if hasattr(kind, "value") else str(kind or "tag")
    return tag_slug_base(params.get("name") or "", params.get("name_en")) or fallback


class Tag(Base):
    """A label events carry: franchise, artist, venue, or group.

    GROUP tags contain member tags (tag_members). Semantics (deliberate):
    attaching a group tag to a concert materializes its members onto the
    concert AT THAT MOMENT (see service.attach_tag). Editors then prune
    non-performers. Later group-membership changes never rewrite existing
    concerts, and notification matching (Phase 10) reads only the
    materialized concert_tags rows.
    """

    __tablename__ = "tags"

    id: Mapped[int] = mapped_column(primary_key=True)
    # The stable identity, and the ONLY unique column here. Names are NOT unique
    # and never will be: two performers may genuinely share one, and a venue may
    # share one with a group (owner ruling, 2026-07-29). So a name cannot
    # identify a tag and nothing may treat it as if it could. Auto-generated via
    # service.assign_tag_slug, editable, ASCII by construction, and deliberately
    # absent from every URL -- tag pages stay on the numeric id. This is what
    # catalogue export/import key on.
    slug: Mapped[str] = mapped_column(String(100), unique=True, default=_derive_tag_slug)
    name: Mapped[str] = mapped_column(String(100))
    # Viewer-locale variants of the tag name. Like `name`, not unique.
    name_en: Mapped[str | None] = mapped_column(String(100))
    name_zh: Mapped[str | None] = mapped_column(String(100))
    kind: Mapped[TagKind] = mapped_column(
        Enum(TagKind, values_callable=lambda e: [m.value for m in e])
    )
    # GROUP tags may belong to a FRANCHISE tag (Hasunosora -> Love Live!, etc.)
    parent_id: Mapped[int | None] = mapped_column(ForeignKey("tags.id", ondelete="SET NULL"))
    # VENUE-specific (harmless if unset on other kinds): a maps/location link,
    # and a free-text region so venues can be browsed/filtered by area instead
    # of one-by-one ("Kanto", "Kansai", etc.)
    location_url: Mapped[str | None] = mapped_column(String(500))
    region: Mapped[str | None] = mapped_column(String(100))
    # VENUE-specific: the city this venue sits in, finer-grained than `region`
    # ("Yokohama" inside "Kanto"). Carries locale variants because a city name
    # is user-facing text; `address` does not, because its job is to be pasted
    # into a map and location_url already covers the maps link.
    city: Mapped[str | None] = mapped_column(String(100))
    city_en: Mapped[str | None] = mapped_column(String(100))
    city_zh: Mapped[str | None] = mapped_column(String(100))
    address: Mapped[str | None] = mapped_column(String(300))
    # ARTIST/GROUP-specific (harmless if unset on other kinds): an
    # eventernote.com link, mirroring location_url for venues so performer
    # chips can link out.
    eventernote_url: Mapped[str | None] = mapped_column(String(500))
    # SET NULL on erasure (see Concert.created_by): tags are shared taxonomy,
    # not personal data -- they outlive the account that first added them.
    created_by: Mapped[int | None] = mapped_column(
        BigInteger, ForeignKey("users.discord_id", ondelete="SET NULL")
    )
    created_at: Mapped[datetime] = mapped_column(UTCDateTime, default=_now)

    members: Mapped[list["Tag"]] = relationship(
        secondary="tag_members",
        primaryjoin="Tag.id == TagMember.group_tag_id",
        secondaryjoin="Tag.id == TagMember.member_tag_id",
        order_by="Tag.name",
    )


class TagMember(Base):
    """group tag ⊇ member tag (artists inside a group). No nested groups."""

    __tablename__ = "tag_members"

    group_tag_id: Mapped[int] = mapped_column(
        ForeignKey("tags.id", ondelete="CASCADE"), primary_key=True
    )
    member_tag_id: Mapped[int] = mapped_column(
        ForeignKey("tags.id", ondelete="CASCADE"), primary_key=True
    )


class ConcertTag(Base):
    __tablename__ = "concert_tags"

    concert_id: Mapped[int] = mapped_column(
        ForeignKey("concerts.id", ondelete="CASCADE"), primary_key=True
    )
    # index=True alongside primary_key=True: the composite PK only indexes
    # (concert_id, tag_id) as a leftmost prefix, so filtering by tag_id alone
    # (the sidebar's tag/region filter) needs its own index.
    tag_id: Mapped[int] = mapped_column(
        ForeignKey("tags.id", ondelete="CASCADE"), primary_key=True, index=True
    )


class ConcertDay(Base):
    __tablename__ = "concert_days"

    id: Mapped[int] = mapped_column(primary_key=True)
    concert_id: Mapped[int] = mapped_column(
        ForeignKey("concerts.id", ondelete="CASCADE"), index=True
    )
    label: Mapped[str] = mapped_column(String(100))  # "Day 1", "Day 2 夜公演"
    # Viewer-locale variants of the leg label; ja IS the original column (see
    # i18n.loc_field). Nullable and never backfilled -- an unfilled variant
    # falls through to the original.
    label_en: Mapped[str | None] = mapped_column(String(100))
    label_zh: Mapped[str | None] = mapped_column(String(100))
    # The structured venue, and the ONLY one anything reads for display. It
    # replaced a free-text venue resolved against VENUE tags by
    # case-insensitive name match, and is made authoritative: matching by name
    # left a re-pointed leg rendering its previous venue forever.
    # SET NULL rather than CASCADE: a venue tag is shared
    # taxonomy, and deleting one must never take performances down with it.
    venue_tag_id: Mapped[int | None] = mapped_column(
        ForeignKey("tags.id", ondelete="SET NULL"), index=True
    )
    doors_at_utc: Mapped[datetime | None] = mapped_column(UTCDateTime)
    starts_at_utc: Mapped[datetime] = mapped_column(UTCDateTime)
    # A cancelled leg is never deleted (its rounds' applies_to would dangle --
    # see docs/superpowers/specs/2026-07-17-cancelled-leg-status-design.md)
    # -- only marked. Rounds have no status field of their own: a round is
    # implicitly cancelled when every ConcertDay id in its applies_to is
    # cancelled ("General" rounds with no day association are never
    # auto-cancelled this way).
    cancelled: Mapped[bool] = mapped_column(default=False, server_default="0")

    concert: Mapped[Concert] = relationship(back_populates="days")
    # Always eager-load this before handing a day to a template -- a lazy load
    # during async rendering raises MissingGreenlet (a 500). See
    # concerts.py's concert_rounds_context.
    venue_tag: Mapped["Tag | None"] = relationship(lazy="raise")


class Round(Base):
    """A deadline round: up to 4 timestamps (apply-opens, apply-closes,
    results, payment-deadline), all optional -- a round can be as simple as
    one open/close sale window, or carry the full lottery lifecycle in one
    row. `kind` classifies the round independent of which timestamps are
    filled in (see RoundKind)."""

    __tablename__ = "rounds"

    id: Mapped[int] = mapped_column(primary_key=True)
    concert_id: Mapped[int] = mapped_column(
        ForeignKey("concerts.id", ondelete="CASCADE"), index=True
    )
    kind: Mapped[RoundKind] = mapped_column(
        Enum(RoundKind, values_callable=lambda e: [m.value for m in e])
    )
    label: Mapped[str] = mapped_column(String(200))  # "最速先行 Round 1", "Day 2 配信"
    # Viewer-locale variants. label_en PREDATES the i18n layer -- it was an
    # English gloss rendered to every viewer at once. It is now a true locale
    # variant selected by loc_field; existing values are already English, so
    # they carry over unchanged.
    label_en: Mapped[str | None] = mapped_column(String(200))
    label_zh: Mapped[str | None] = mapped_column(String(200))
    opens_at_utc: Mapped[datetime | None] = mapped_column(UTCDateTime)
    closes_at_utc: Mapped[datetime | None] = mapped_column(UTCDateTime)
    results_at_utc: Mapped[datetime | None] = mapped_column(UTCDateTime)
    payment_deadline_at_utc: Mapped[datetime | None] = mapped_column(UTCDateTime)
    applies_to: Mapped[list | None] = mapped_column(JSON)  # optional concert_day ids
    url: Mapped[str | None] = mapped_column(String(500))
    notes: Mapped[str | None] = mapped_column(Text)

    concert: Mapped[Concert] = relationship(back_populates="rounds")
    # Qualifying rounds for an UPGRADE round (see RoundQualifier). Meaningful
    # only when kind == UPGRADE; an empty list means "any secured ticket on
    # this concert qualifies" (mirrors applies_to's empty-means-all). CASCADE
    # on the association rows keeps this list free of dangling ids.
    qualifiers: Mapped[list["Round"]] = relationship(
        secondary="round_qualifiers",
        primaryjoin="Round.id == RoundQualifier.upgrade_round_id",
        secondaryjoin="Round.id == RoundQualifier.qualifying_round_id",
    )


class RoundQualifier(Base):
    """upgrade round ⊇ qualifying round: which rounds' ticket-holders may
    enter an UPGRADE round. Modelled on TagMember -- a plain two-column
    association table with a composite primary key (so the pair is unique)
    and both foreign keys ON DELETE CASCADE. Deleting either the upgrade
    round or a qualifying round removes the link automatically, so readers
    never see a dangling id. No qualifier rows for an upgrade round means
    "any secured ticket on this concert qualifies"."""

    __tablename__ = "round_qualifiers"

    upgrade_round_id: Mapped[int] = mapped_column(
        ForeignKey("rounds.id", ondelete="CASCADE"), primary_key=True
    )
    qualifying_round_id: Mapped[int] = mapped_column(
        ForeignKey("rounds.id", ondelete="CASCADE"), primary_key=True
    )


class RoundLabelPhrase(Base):
    """A trilingual round label the editor has used before, offered as a
    one-click suggestion on later concerts.

    Round labels do not decompose into a taxonomy -- real ones carry a
    CHANNEL (オフィシャル, ファミリーマート, 「Liella! CLUB 2025」) that is a
    proper noun, so no enum can enumerate them. Remembering whole triples
    sidesteps that: the app never parses a label, it just recalls one.

    The unique index spans all three columns, so a corrected phrase and the
    typo it replaces are separate rows -- forgetting the typo is a delete,
    not an edit, and never touches concerts that already used it.
    """

    __tablename__ = "round_label_phrases"
    __table_args__ = (
        Index("uq_round_label_phrase", "label", "label_en", "label_zh", unique=True),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    label: Mapped[str] = mapped_column(String(200))
    label_en: Mapped[str] = mapped_column(String(200))
    label_zh: Mapped[str] = mapped_column(String(200))
    # Ranking inputs. used_count is bumped on every save that reuses the
    # triple; last_used_at breaks ties so a recently-revived phrase outranks
    # an equally-used stale one.
    used_count: Mapped[int] = mapped_column(default=1, server_default="1")
    created_at: Mapped[datetime] = mapped_column(UTCDateTime, default=_now)
    last_used_at: Mapped[datetime] = mapped_column(UTCDateTime, default=_now)


class RoundOutcome(Base):
    """One user's recorded progress through a specific round's lottery:
    NOT_APPLIED (explicitly opted out) / APPLIED / WON / LOST / PAID.
    Strict sequence enforced in record_round_outcome, not at the DB layer:
    APPLIED -> (WON | LOST) -> PAID (PAID only reachable from WON)."""

    __tablename__ = "round_outcomes"
    __table_args__ = (Index("uq_round_outcome", "user_id", "round_id", unique=True),)

    id: Mapped[int] = mapped_column(primary_key=True)
    user_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("users.discord_id", ondelete="CASCADE")
    )
    round_id: Mapped[int] = mapped_column(ForeignKey("rounds.id", ondelete="CASCADE"))
    outcome: Mapped[LotteryOutcome] = mapped_column(
        Enum(LotteryOutcome, values_callable=lambda e: [m.value for m in e])
    )
    updated_at: Mapped[datetime] = mapped_column(UTCDateTime, default=_now, onupdate=_now)


class RoundOutcomeDay(Base):
    """Per-day resolution of one user's round outcome. No-rows-means-all
    convention (mirrors applies_to / round_qualifiers): a round outcome of
    WON with zero rows here means every covered day was won; rows exist only
    when resolution is explicit/partial. "Not going" is NOT stored here --
    that is LegOptOut's job."""

    __tablename__ = "round_outcome_days"
    __table_args__ = (
        Index("uq_round_outcome_day", "user_id", "round_id", "day_id", unique=True),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    user_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("users.discord_id", ondelete="CASCADE")
    )
    round_id: Mapped[int] = mapped_column(ForeignKey("rounds.id", ondelete="CASCADE"))
    day_id: Mapped[int] = mapped_column(ForeignKey("concert_days.id", ondelete="CASCADE"))
    result: Mapped[LegResult] = mapped_column(
        Enum(LegResult, values_callable=lambda e: [m.value for m in e])
    )
    updated_at: Mapped[datetime] = mapped_column(UTCDateTime, default=_now, onupdate=_now)


class ConcertSubscription(Base):
    """A user's explicit per-concert override on the tag-derived default.

    Overrides, not materialised records: NO row = follow the tag default
    (today's behaviour, no backfill needed); a `subscribed` row forces the
    concert onto the board even with no matching tag; an `opted_out` row
    prunes it even though a tag matches. Rows exist only when a user acts, so
    there is no write amplification and every existing board keeps working
    through the same derivation. Consumed by `tracked_concert_ids`.
    See specs/2026-07-19-concert-subscriptions-design.md.
    """

    __tablename__ = "concert_subscriptions"
    __table_args__ = (Index("uq_concert_subscription", "user_id", "concert_id", unique=True),)

    id: Mapped[int] = mapped_column(primary_key=True)
    user_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("users.discord_id", ondelete="CASCADE")
    )
    concert_id: Mapped[int] = mapped_column(ForeignKey("concerts.id", ondelete="CASCADE"))
    state: Mapped[SubscriptionState] = mapped_column(
        Enum(SubscriptionState, values_callable=lambda e: [m.value for m in e])
    )
    created_at: Mapped[datetime] = mapped_column(UTCDateTime, default=_now)


class LegOptOut(Base):
    """A user's per-leg opt-out: presence of a row means opted out of that
    ConcertDay, absence means the leg follows its concert (the default). One
    level down from ConcertSubscription and needs no state column. Its rounds
    are suppressed for this user in the same read-side pass cancellation and
    outcomes use (invariant 2)."""

    __tablename__ = "leg_opt_outs"
    __table_args__ = (Index("uq_leg_opt_out", "user_id", "concert_day_id", unique=True),)

    id: Mapped[int] = mapped_column(primary_key=True)
    user_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("users.discord_id", ondelete="CASCADE")
    )
    concert_day_id: Mapped[int] = mapped_column(
        ForeignKey("concert_days.id", ondelete="CASCADE")
    )
    created_at: Mapped[datetime] = mapped_column(UTCDateTime, default=_now)


class ReminderRule(Base):
    __tablename__ = "reminder_rules"

    id: Mapped[int] = mapped_column(primary_key=True)
    user_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("users.discord_id", ondelete="CASCADE")
    )
    # Exactly one of these is set: concert-wide rule, or one-round rule.
    concert_id: Mapped[int | None] = mapped_column(
        ForeignKey("concerts.id", ondelete="CASCADE"), index=True
    )
    round_id: Mapped[int | None] = mapped_column(
        ForeignKey("rounds.id", ondelete="CASCADE"), index=True
    )

    anchor: Mapped[Anchor] = mapped_column(
        Enum(Anchor, values_callable=lambda e: [m.value for m in e])
    )
    offset_days: Mapped[int] = mapped_column(default=-1)  # negative = before
    offset_hours: Mapped[int] = mapped_column(default=0)
    channel: Mapped[Channel] = mapped_column(
        Enum(Channel, values_callable=lambda e: [m.value for m in e]), default=Channel.DM
    )
    channel_id: Mapped[int | None] = mapped_column(BigInteger)  # when channel=CHANNEL
    created_at: Mapped[datetime] = mapped_column(UTCDateTime, default=_now)

    user: Mapped[User] = relationship(back_populates="rules")


class ReminderPreset(Base):
    """A user's named reminder loadout, e.g. 'standard lottery coverage'."""

    __tablename__ = "reminder_presets"

    id: Mapped[int] = mapped_column(primary_key=True)
    user_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("users.discord_id", ondelete="CASCADE")
    )
    name: Mapped[str] = mapped_column(String(100))
    # The preset the "Set my reminders" DM button applies. One per user.
    is_default: Mapped[bool] = mapped_column(default=False, server_default="0")
    created_at: Mapped[datetime] = mapped_column(UTCDateTime, default=_now)

    items: Mapped[list["PresetItem"]] = relationship(
        cascade="all, delete-orphan", order_by="PresetItem.id"
    )


class PresetItem(Base):
    """One rule template inside a preset: '3 days before each close', etc."""

    __tablename__ = "preset_items"

    id: Mapped[int] = mapped_column(primary_key=True)
    preset_id: Mapped[int] = mapped_column(
        ForeignKey("reminder_presets.id", ondelete="CASCADE")
    )
    anchor: Mapped[Anchor] = mapped_column(
        Enum(Anchor, values_callable=lambda e: [m.value for m in e])
    )
    offset_days: Mapped[int] = mapped_column(default=-3)
    offset_hours: Mapped[int] = mapped_column(default=0)


class TagSubscription(Base):
    """User follows a tag. When a matching event appears: preset auto-applies
    (if linked) and a DM notice goes out (if notify). Agreed default:
    notify-and-apply, both toggleable per subscription."""

    __tablename__ = "tag_subscriptions"
    __table_args__ = (Index("uq_tag_sub", "user_id", "tag_id", unique=True),)

    id: Mapped[int] = mapped_column(primary_key=True)
    user_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("users.discord_id", ondelete="CASCADE")
    )
    tag_id: Mapped[int] = mapped_column(ForeignKey("tags.id", ondelete="CASCADE"))
    preset_id: Mapped[int | None] = mapped_column(
        ForeignKey("reminder_presets.id", ondelete="SET NULL")
    )
    notify: Mapped[bool] = mapped_column(default=True, server_default="1")
    created_at: Mapped[datetime] = mapped_column(UTCDateTime, default=_now)


class Broadcast(Base):
    """The permanent audit record of one admin broadcast.

    NEVER pruned, unlike delivery_log's 30-day window: this records an admin
    action against other people's DMs, not a delivery. "Did we already tell
    them?" must stay answerable indefinitely.
    """

    __tablename__ = "broadcasts"

    id: Mapped[int] = mapped_column(primary_key=True)
    # SET NULL, matching Concert.created_by: erasing the admin's account keeps
    # the record of what they did and anonymizes who did it.
    created_by: Mapped[int | None] = mapped_column(
        BigInteger, ForeignKey("users.discord_id", ondelete="SET NULL")
    )
    created_at_utc: Mapped[datetime] = mapped_column(UTCDateTime, default=_now)
    mode: Mapped[BroadcastMode] = mapped_column(
        Enum(BroadcastMode, values_callable=lambda e: [m.value for m in e])
    )
    # The batch timestamp, the raw id list as typed, or NULL for ALL.
    mode_param: Mapped[str | None] = mapped_column(Text)
    body: Mapped[str] = mapped_column(Text)
    # What was actually queued, not what the preview showed.
    recipient_count: Mapped[int] = mapped_column()
    send_after_utc: Mapped[datetime] = mapped_column(UTCDateTime)
    cancelled_at_utc: Mapped[datetime | None] = mapped_column(UTCDateTime)


class Notification(Base):
    """One-off DM outbox (new-event notices). Drained by the scheduler like
    reminder_queue: only successful delivery marks sent, so notices survive
    restarts and web-only mode queues them until the bot is back."""

    __tablename__ = "notifications"

    id: Mapped[int] = mapped_column(primary_key=True)
    user_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("users.discord_id", ondelete="CASCADE")
    )
    body: Mapped[str] = mapped_column(Text)  # plain-text fallback if embed context fails
    # Structured payload: when concert_id is set, the scheduler renders a rich
    # embed with buttons instead of plain text.
    concert_id: Mapped[int | None] = mapped_column(
        ForeignKey("concerts.id", ondelete="CASCADE")
    )
    kind: Mapped[str | None] = mapped_column(String(30))  # "new_event"
    # Both nullable, and NULL means exactly the pre-broadcast behaviour --
    # which is what keeps new_event, leg_cancelled, ops_alert and
    # delivery_digest untouched by a change to the drain query they all use.
    #
    # send_after_utc holds a row back until its moment: it is what turns an
    # unrecallable mass DM into one that can be cancelled for two minutes.
    send_after_utc: Mapped[datetime | None] = mapped_column(UTCDateTime)
    # SET NULL, not CASCADE: a queued notice is something that happened to a
    # user, and deleting the audit row should not erase it.
    broadcast_id: Mapped[int | None] = mapped_column(
        ForeignKey("broadcasts.id", ondelete="SET NULL")
    )
    created_at: Mapped[datetime] = mapped_column(UTCDateTime, default=_now)
    sent_at_utc: Mapped[datetime | None] = mapped_column(UTCDateTime)


class DeliveryLog(Base):
    """One row per attempted DM delivery, reminders and notifications alike.

    Durable on purpose. reminder_queue can already answer "who was DMed about
    this" by joining rule_id -> reminder_rules -> users, but those rows are
    not evidence: sync_rule deletes rows it no longer plans and a deleted
    round cascades them away, so the trail vanishes exactly when a bad
    concert edit is the thing being investigated.

    Hence the two shapes of column below. The labels are DENORMALIZED text so
    a row survives its catalogue being edited or deleted; the *_id columns are
    convenience pointers for linking through while the entity still exists,
    and are SET NULL rather than CASCADE for the same reason
    Concert.created_by is (keep the record, drop the pointer).

    user_id is CASCADE, and that is not optional: this table records which
    events a named person was reminded about, and delete_user is a single
    session.delete relying on cascades (invariant 5).
    """

    __tablename__ = "delivery_log"

    id: Mapped[int] = mapped_column(primary_key=True)
    # The tick's `now`. Doubles as the batch identity -- there is deliberately
    # no delivery_batches table, so aggregates compute on read and no stored
    # count can drift from the rows it summarizes.
    batch_at_utc: Mapped[datetime] = mapped_column(UTCDateTime, index=True)
    user_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("users.discord_id", ondelete="CASCADE")
    )
    source: Mapped[DeliverySource] = mapped_column(
        Enum(DeliverySource, values_callable=lambda e: [m.value for m in e])
    )
    outcome: Mapped[DeliveryOutcome] = mapped_column(
        Enum(DeliveryOutcome, values_callable=lambda e: [m.value for m in e])
    )
    # Reminder rows only.
    anchor: Mapped[Anchor | None] = mapped_column(
        Enum(Anchor, values_callable=lambda e: [m.value for m in e])
    )
    # Notification rows only: the Notification.kind that was delivered.
    note_kind: Mapped[str | None] = mapped_column(String(30))
    concert_title: Mapped[str | None] = mapped_column(String(300))
    leg_label: Mapped[str | None] = mapped_column(String(200))
    round_label: Mapped[str | None] = mapped_column(String(200))
    concert_id: Mapped[int | None] = mapped_column(
        ForeignKey("concerts.id", ondelete="SET NULL")
    )
    round_id: Mapped[int | None] = mapped_column(ForeignKey("rounds.id", ondelete="SET NULL"))
    day_id: Mapped[int | None] = mapped_column(
        ForeignKey("concert_days.id", ondelete="SET NULL")
    )
    sent_at_utc: Mapped[datetime] = mapped_column(UTCDateTime)


class ReminderQueue(Base):
    """Materialized outbox. The scheduler's entire job is draining this table.

    Idempotency: the functional unique index below treats NULL round/day as 0,
    so re-planning after an edit UPSERTS instead of duplicating. (Plain SQLite
    UNIQUE constraints consider NULLs distinct — the coalesce() sidesteps that.)
    """

    __tablename__ = "reminder_queue"
    __table_args__ = (
        Index(
            "uq_reminder_queue_dedupe",
            "rule_id",
            text("coalesce(round_id, 0)"),
            text("coalesce(day_id, 0)"),
            "anchor",
            unique=True,
        ),
        Index("ix_reminder_queue_due", "sent_at_utc", "fire_at_utc"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    rule_id: Mapped[int] = mapped_column(ForeignKey("reminder_rules.id", ondelete="CASCADE"))
    round_id: Mapped[int | None] = mapped_column(ForeignKey("rounds.id", ondelete="CASCADE"))
    day_id: Mapped[int | None] = mapped_column(ForeignKey("concert_days.id", ondelete="CASCADE"))
    anchor: Mapped[Anchor] = mapped_column(
        Enum(Anchor, values_callable=lambda e: [m.value for m in e])
    )
    fire_at_utc: Mapped[datetime] = mapped_column(UTCDateTime)
    sent_at_utc: Mapped[datetime | None] = mapped_column(UTCDateTime)


class OpsCheckState(Base):
    """Last confirmed result per operational check, so alerting survives
    restarts. In-memory state would re-announce every problem on every deploy.

    Mirrors domain.health.StoredState, which is a plain dataclass -- domain/
    cannot import sqlalchemy, so ops.py converts between the two.
    """

    __tablename__ = "ops_check_state"

    name: Mapped[str] = mapped_column(String(40), primary_key=True)
    ok: Mapped[bool | None] = mapped_column(Boolean)
    changed_at: Mapped[datetime | None] = mapped_column(UTCDateTime)
    last_notified_at: Mapped[datetime | None] = mapped_column(UTCDateTime)
    pending_ok: Mapped[bool | None] = mapped_column(Boolean)
    pending_since: Mapped[datetime | None] = mapped_column(UTCDateTime)
