"""Database schema (SQLAlchemy 2.0 typed style).

Design recap (see README):
  concerts ─┬─ concert_days      "Day 1", 昼公演/夜公演 — actual show datetimes
            └─ rounds            generic typed deadline rounds (lotteries, sales...)
  users ──── reminder_rules      "remind me N days before/after X"
  reminder_queue                 materialized outbox the scheduler drains

Timezone rule enforced HERE, at the boundary: the UTCDateTime type refuses
naive datetimes on write and always returns aware-UTC on read. SQLite itself
has no timezone concept, so we make the ORM the gatekeeper.
"""

from datetime import UTC, datetime

from sqlalchemy import (
    JSON,
    BigInteger,
    DateTime,
    Enum,
    ForeignKey,
    Index,
    MetaData,
    String,
    Text,
    TypeDecorator,
    text,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship

from app.domain.types import Anchor, Channel, ConcertKind, LotteryOutcome, RoundKind, TagKind


class UTCDateTime(TypeDecorator):
    """Store aware-UTC datetimes in SQLite; reject naive ones loudly."""

    impl = DateTime
    cache_ok = True

    def process_bind_param(self, value: datetime | None, dialect):
        if value is None:
            return None
        if value.tzinfo is None:
            raise ValueError("naive datetime rejected — store timezone-aware UTC only")
        return value.astimezone(UTC).replace(tzinfo=None)  # normalized, stored naive

    def process_result_value(self, value: datetime | None, dialect):
        return value.replace(tzinfo=UTC) if value is not None else None


# Every constraint gets a deterministic name. SQLite migrations run in
# batch (table-rebuild) mode, which refuses unnamed constraints - this
# convention makes autogenerated migrations safe by construction.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


def _now() -> datetime:
    return datetime.now(UTC)


class User(Base):
    __tablename__ = "users"

    discord_id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=False)
    username: Mapped[str] = mapped_column(String(100))
    avatar_hash: Mapped[str | None] = mapped_column(String(64))
    timezone: Mapped[str] = mapped_column(String(64), default="America/Moncton")
    # tz_auto: timezone is browser-detected until the user overrides it manually
    tz_auto: Mapped[bool] = mapped_column(default=True, server_default="1")
    # DB-persisted editor grant, toggled by admins (web/Discord). Final editor
    # status is this OR settings.editor_whitelist OR settings.admin_whitelist.
    is_editor: Mapped[bool] = mapped_column(default=False, server_default="0")
    # Personal calendar-feed subscription token, hashed at rest (same pattern
    # as WebSession.token_hash) -- the raw token lives only in the feed URL,
    # shown once at generation time, never stored or re-displayable.
    calendar_token_hash: Mapped[str | None] = mapped_column(String(64), unique=True)
    # None = DMs working (or never tested); a timestamp = the most recent
    # attempted send hit discord.Forbidden. One shared signal across both
    # reminder-DM and notification-DM sends (see scheduler/loop.py's
    # DeliveryOutcome and db/service.py's record_dm_outcome). Surfaced as a
    # sitewide banner via auth.SessionUser.dm_blocked.
    dm_blocked_since: Mapped[datetime | None] = mapped_column(UTCDateTime)
    # First-run guided setup: 0-4 = the wizard step in progress, >=5 = done
    # (finished naturally or skipped). Offered once at first login only --
    # never re-derived from this value on any later login.
    onboarding_step: Mapped[int] = mapped_column(default=0, server_default="0")
    created_at: Mapped[datetime] = mapped_column(UTCDateTime, default=_now)

    # passive_deletes: reminder_rules.user_id is NOT NULL with ondelete=CASCADE,
    # so let the DB delete the children. Without this the ORM tries to UPDATE
    # them to user_id=NULL first and deleting a user fails (see delete_user).
    rules: Mapped[list["ReminderRule"]] = relationship(
        back_populates="user", passive_deletes=True
    )


class WebSession(Base):
    """Server-side login sessions: revocable, expiring, replay-proof.

    The cookie carries an opaque random token; only its SHA-256 lands here,
    so a leaked database cannot be turned back into usable cookies.
    Logout revokes the row -> a replayed cookie is dead server-side.
    """

    __tablename__ = "web_sessions"

    id: Mapped[int] = mapped_column(primary_key=True)
    token_hash: Mapped[str] = mapped_column(String(64), unique=True)
    user_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("users.discord_id", ondelete="CASCADE")
    )
    created_at: Mapped[datetime] = mapped_column(UTCDateTime, default=_now)
    expires_at: Mapped[datetime] = mapped_column(UTCDateTime)
    revoked_at: Mapped[datetime | None] = mapped_column(UTCDateTime)


class Concert(Base):
    __tablename__ = "concerts"

    id: Mapped[int] = mapped_column(primary_key=True)
    # URL-facing handle, distinct from the internal PK (which every FK still
    # targets). Editor-chosen at creation; existing concerts were backfilled
    # to str(id) so old links keep resolving.
    event_id: Mapped[str] = mapped_column(String(100), unique=True)
    title: Mapped[str] = mapped_column(String(200))
    title_en: Mapped[str | None] = mapped_column(String(200))
    kind: Mapped[ConcertKind | None] = mapped_column(
        Enum(ConcertKind, values_callable=lambda e: [m.value for m in e])
    )
    organizer: Mapped[str | None] = mapped_column(String(200))  # free-text artist/organizer
    categories: Mapped[str | None] = mapped_column(String(300))  # comma-sep free text
    eventernote_url: Mapped[str | None] = mapped_column(String(500))
    official_url: Mapped[str | None] = mapped_column(String(500))
    source_url: Mapped[str | None] = mapped_column(String(500))
    performers_text: Mapped[str | None] = mapped_column(Text)  # free-text, one per line
    franchise: Mapped[str | None] = mapped_column(String(100))  # "Hasunosora", "Gakumas"...
    venue: Mapped[str | None] = mapped_column(String(200))
    notes: Mapped[str | None] = mapped_column(Text)
    # SET NULL, not CASCADE: erasing the editor who filed a concert must not
    # delete the shared catalogue entry everyone else follows. NULL = the
    # author was deleted (GDPR erasure) -- see service.delete_user.
    created_by: Mapped[int | None] = mapped_column(
        BigInteger, ForeignKey("users.discord_id", ondelete="SET NULL")
    )
    created_at: Mapped[datetime] = mapped_column(UTCDateTime, default=_now)

    creator: Mapped["User | None"] = relationship()  # also fixes ORM insert ordering
    days: Mapped[list["ConcertDay"]] = relationship(
        back_populates="concert", cascade="all, delete-orphan", order_by="ConcertDay.starts_at_utc"
    )
    rounds: Mapped[list["Round"]] = relationship(
        back_populates="concert", cascade="all, delete-orphan"
    )
    tags: Mapped[list["Tag"]] = relationship(secondary="concert_tags", order_by="Tag.name")
    audits: Mapped[list["ConcertAudit"]] = relationship(
        cascade="all, delete-orphan", order_by="ConcertAudit.edited_at_utc.desc()"
    )


class ConcertAudit(Base):
    """One row per edit that actually changed a tracked scalar field --
    lightweight by design: only the concert's own top-level fields (title,
    organizer, URLs, notes, ...), not day/round/tag adds-and-removes. `changes`
    is a JSON list of {"field", "before", "after"}; enum values are stored as
    their plain `.value` string so the column stays JSON-serializable."""

    __tablename__ = "concert_audit"

    id: Mapped[int] = mapped_column(primary_key=True)
    concert_id: Mapped[int] = mapped_column(
        ForeignKey("concerts.id", ondelete="CASCADE"), index=True
    )
    # SET NULL on erasure (see Concert.created_by): the edit itself stays in
    # the history, its author anonymised.
    edited_by: Mapped[int | None] = mapped_column(
        BigInteger, ForeignKey("users.discord_id", ondelete="SET NULL")
    )
    edited_at_utc: Mapped[datetime] = mapped_column(UTCDateTime, default=_now)
    changes: Mapped[list] = mapped_column(JSON)

    editor: Mapped["User | None"] = relationship()


class Tag(Base):
    """A label events carry: franchise, artist, venue, or group.

    GROUP tags contain member tags (tag_members). Semantics (deliberate):
    attaching a group tag to a concert materializes its members onto the
    concert AT THAT MOMENT (see service.attach_tag). Editors then prune
    non-performers. Later group-membership changes never rewrite existing
    concerts, and notification matching (Phase 10) reads only the
    materialized concert_tags rows.
    """

    __tablename__ = "tags"

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(100), unique=True)
    kind: Mapped[TagKind] = mapped_column(
        Enum(TagKind, values_callable=lambda e: [m.value for m in e])
    )
    # GROUP tags may belong to a FRANCHISE tag (Hasunosora -> Love Live!, etc.)
    parent_id: Mapped[int | None] = mapped_column(ForeignKey("tags.id", ondelete="SET NULL"))
    # VENUE-specific (harmless if unset on other kinds): a maps/location link,
    # and a free-text region so venues can be browsed/filtered by area instead
    # of one-by-one ("Kanto", "Kansai", etc.)
    location_url: Mapped[str | None] = mapped_column(String(500))
    region: Mapped[str | None] = mapped_column(String(100))
    # SET NULL on erasure (see Concert.created_by): tags are shared taxonomy,
    # not personal data -- they outlive the account that first added them.
    created_by: Mapped[int | None] = mapped_column(
        BigInteger, ForeignKey("users.discord_id", ondelete="SET NULL")
    )
    created_at: Mapped[datetime] = mapped_column(UTCDateTime, default=_now)

    members: Mapped[list["Tag"]] = relationship(
        secondary="tag_members",
        primaryjoin="Tag.id == TagMember.group_tag_id",
        secondaryjoin="Tag.id == TagMember.member_tag_id",
        order_by="Tag.name",
    )


class TagMember(Base):
    """group tag ⊇ member tag (artists inside a group). No nested groups."""

    __tablename__ = "tag_members"

    group_tag_id: Mapped[int] = mapped_column(
        ForeignKey("tags.id", ondelete="CASCADE"), primary_key=True
    )
    member_tag_id: Mapped[int] = mapped_column(
        ForeignKey("tags.id", ondelete="CASCADE"), primary_key=True
    )


class ConcertTag(Base):
    __tablename__ = "concert_tags"

    concert_id: Mapped[int] = mapped_column(
        ForeignKey("concerts.id", ondelete="CASCADE"), primary_key=True
    )
    # index=True alongside primary_key=True: the composite PK only indexes
    # (concert_id, tag_id) as a leftmost prefix, so filtering by tag_id alone
    # (the sidebar's tag/region filter) needs its own index.
    tag_id: Mapped[int] = mapped_column(
        ForeignKey("tags.id", ondelete="CASCADE"), primary_key=True, index=True
    )


class ConcertDay(Base):
    __tablename__ = "concert_days"

    id: Mapped[int] = mapped_column(primary_key=True)
    concert_id: Mapped[int] = mapped_column(
        ForeignKey("concerts.id", ondelete="CASCADE"), index=True
    )
    label: Mapped[str] = mapped_column(String(100))  # "Day 1", "Day 2 夜公演"
    city: Mapped[str | None] = mapped_column(String(100))  # leg/city, e.g. "Kanagawa"
    venue: Mapped[str | None] = mapped_column(String(200))  # per-day venue (tours change cities)
    venue_address: Mapped[str | None] = mapped_column(String(300))
    doors_at_utc: Mapped[datetime | None] = mapped_column(UTCDateTime)
    starts_at_utc: Mapped[datetime] = mapped_column(UTCDateTime)
    # A cancelled leg is never deleted (its rounds' applies_to would dangle --
    # see docs/superpowers/specs/2026-07-17-cancelled-leg-status-design.md)
    # -- only marked. Rounds have no status field of their own: a round is
    # implicitly cancelled when every ConcertDay id in its applies_to is
    # cancelled ("General" rounds with no day association are never
    # auto-cancelled this way).
    cancelled: Mapped[bool] = mapped_column(default=False, server_default="0")

    concert: Mapped[Concert] = relationship(back_populates="days")


class Round(Base):
    """A deadline round: up to 4 timestamps (apply-opens, apply-closes,
    results, payment-deadline), all optional -- a round can be as simple as
    one open/close sale window, or carry the full lottery lifecycle in one
    row. `kind` classifies the round independent of which timestamps are
    filled in (see RoundKind)."""

    __tablename__ = "rounds"

    id: Mapped[int] = mapped_column(primary_key=True)
    concert_id: Mapped[int] = mapped_column(
        ForeignKey("concerts.id", ondelete="CASCADE"), index=True
    )
    kind: Mapped[RoundKind] = mapped_column(
        Enum(RoundKind, values_callable=lambda e: [m.value for m in e])
    )
    label: Mapped[str] = mapped_column(String(200))  # "最速先行 Round 1", "Day 2 配信"
    label_en: Mapped[str | None] = mapped_column(String(200))
    opens_at_utc: Mapped[datetime | None] = mapped_column(UTCDateTime)
    closes_at_utc: Mapped[datetime | None] = mapped_column(UTCDateTime)
    results_at_utc: Mapped[datetime | None] = mapped_column(UTCDateTime)
    payment_deadline_at_utc: Mapped[datetime | None] = mapped_column(UTCDateTime)
    applies_to: Mapped[list | None] = mapped_column(JSON)  # optional concert_day ids
    url: Mapped[str | None] = mapped_column(String(500))
    notes: Mapped[str | None] = mapped_column(Text)

    concert: Mapped[Concert] = relationship(back_populates="rounds")


class RoundOutcome(Base):
    """One user's recorded progress through a specific round's lottery:
    NOT_APPLIED (explicitly opted out) / APPLIED / WON / LOST / PAID.
    Strict sequence enforced in record_round_outcome, not at the DB layer:
    APPLIED -> (WON | LOST) -> PAID (PAID only reachable from WON)."""

    __tablename__ = "round_outcomes"
    __table_args__ = (Index("uq_round_outcome", "user_id", "round_id", unique=True),)

    id: Mapped[int] = mapped_column(primary_key=True)
    user_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("users.discord_id", ondelete="CASCADE")
    )
    round_id: Mapped[int] = mapped_column(ForeignKey("rounds.id", ondelete="CASCADE"))
    outcome: Mapped[LotteryOutcome] = mapped_column(
        Enum(LotteryOutcome, values_callable=lambda e: [m.value for m in e])
    )
    updated_at: Mapped[datetime] = mapped_column(UTCDateTime, default=_now, onupdate=_now)


class ReminderRule(Base):
    __tablename__ = "reminder_rules"

    id: Mapped[int] = mapped_column(primary_key=True)
    user_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("users.discord_id", ondelete="CASCADE")
    )
    # Exactly one of these is set: concert-wide rule, or one-round rule.
    concert_id: Mapped[int | None] = mapped_column(
        ForeignKey("concerts.id", ondelete="CASCADE"), index=True
    )
    round_id: Mapped[int | None] = mapped_column(
        ForeignKey("rounds.id", ondelete="CASCADE"), index=True
    )

    anchor: Mapped[Anchor] = mapped_column(
        Enum(Anchor, values_callable=lambda e: [m.value for m in e])
    )
    offset_days: Mapped[int] = mapped_column(default=-1)  # negative = before
    offset_hours: Mapped[int] = mapped_column(default=0)
    channel: Mapped[Channel] = mapped_column(
        Enum(Channel, values_callable=lambda e: [m.value for m in e]), default=Channel.DM
    )
    channel_id: Mapped[int | None] = mapped_column(BigInteger)  # when channel=CHANNEL
    created_at: Mapped[datetime] = mapped_column(UTCDateTime, default=_now)

    user: Mapped[User] = relationship(back_populates="rules")


class ReminderPreset(Base):
    """A user's named reminder loadout, e.g. 'standard lottery coverage'."""

    __tablename__ = "reminder_presets"

    id: Mapped[int] = mapped_column(primary_key=True)
    user_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("users.discord_id", ondelete="CASCADE")
    )
    name: Mapped[str] = mapped_column(String(100))
    # The preset the "Set my reminders" DM button applies. One per user.
    is_default: Mapped[bool] = mapped_column(default=False, server_default="0")
    created_at: Mapped[datetime] = mapped_column(UTCDateTime, default=_now)

    items: Mapped[list["PresetItem"]] = relationship(
        cascade="all, delete-orphan", order_by="PresetItem.id"
    )


class PresetItem(Base):
    """One rule template inside a preset: '3 days before each close', etc."""

    __tablename__ = "preset_items"

    id: Mapped[int] = mapped_column(primary_key=True)
    preset_id: Mapped[int] = mapped_column(
        ForeignKey("reminder_presets.id", ondelete="CASCADE")
    )
    anchor: Mapped[Anchor] = mapped_column(
        Enum(Anchor, values_callable=lambda e: [m.value for m in e])
    )
    offset_days: Mapped[int] = mapped_column(default=-3)
    offset_hours: Mapped[int] = mapped_column(default=0)


class TagSubscription(Base):
    """User follows a tag. When a matching event appears: preset auto-applies
    (if linked) and a DM notice goes out (if notify). Agreed default:
    notify-and-apply, both toggleable per subscription."""

    __tablename__ = "tag_subscriptions"
    __table_args__ = (Index("uq_tag_sub", "user_id", "tag_id", unique=True),)

    id: Mapped[int] = mapped_column(primary_key=True)
    user_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("users.discord_id", ondelete="CASCADE")
    )
    tag_id: Mapped[int] = mapped_column(ForeignKey("tags.id", ondelete="CASCADE"))
    preset_id: Mapped[int | None] = mapped_column(
        ForeignKey("reminder_presets.id", ondelete="SET NULL")
    )
    notify: Mapped[bool] = mapped_column(default=True, server_default="1")
    created_at: Mapped[datetime] = mapped_column(UTCDateTime, default=_now)


class Notification(Base):
    """One-off DM outbox (new-event notices). Drained by the scheduler like
    reminder_queue: only successful delivery marks sent, so notices survive
    restarts and web-only mode queues them until the bot is back."""

    __tablename__ = "notifications"

    id: Mapped[int] = mapped_column(primary_key=True)
    user_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("users.discord_id", ondelete="CASCADE")
    )
    body: Mapped[str] = mapped_column(Text)  # plain-text fallback if embed context fails
    # Structured payload: when concert_id is set, the scheduler renders a rich
    # embed with buttons instead of plain text.
    concert_id: Mapped[int | None] = mapped_column(
        ForeignKey("concerts.id", ondelete="CASCADE")
    )
    kind: Mapped[str | None] = mapped_column(String(30))  # "new_event"
    created_at: Mapped[datetime] = mapped_column(UTCDateTime, default=_now)
    sent_at_utc: Mapped[datetime | None] = mapped_column(UTCDateTime)


class ReminderQueue(Base):
    """Materialized outbox. The scheduler's entire job is draining this table.

    Idempotency: the functional unique index below treats NULL round/day as 0,
    so re-planning after an edit UPSERTS instead of duplicating. (Plain SQLite
    UNIQUE constraints consider NULLs distinct — the coalesce() sidesteps that.)
    """

    __tablename__ = "reminder_queue"
    __table_args__ = (
        Index(
            "uq_reminder_queue_dedupe",
            "rule_id",
            text("coalesce(round_id, 0)"),
            text("coalesce(day_id, 0)"),
            "anchor",
            unique=True,
        ),
        Index("ix_reminder_queue_due", "sent_at_utc", "fire_at_utc"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    rule_id: Mapped[int] = mapped_column(ForeignKey("reminder_rules.id", ondelete="CASCADE"))
    round_id: Mapped[int | None] = mapped_column(ForeignKey("rounds.id", ondelete="CASCADE"))
    day_id: Mapped[int | None] = mapped_column(ForeignKey("concert_days.id", ondelete="CASCADE"))
    anchor: Mapped[Anchor] = mapped_column(
        Enum(Anchor, values_callable=lambda e: [m.value for m in e])
    )
    fire_at_utc: Mapped[datetime] = mapped_column(UTCDateTime)
    sent_at_utc: Mapped[datetime | None] = mapped_column(UTCDateTime)
