"""The db layer's import surface: everything `bot/` and `web/` may call.

CLAUDE.md's rule is that bot and web contain no business logic and call
`db/service.py`. This module is what keeps that literally true after the
8,063-line original was split -- every name it ever exported is still
importable from here, so no call site changed and none needs to.

It is a FACADE and holds no logic of its own. The work moved to:

    core.py              the engine: queue sync, retrieval, the personal
                         board, the concert page, Discover status, DM button
                         actions, presets/subscriptions, users, adapters
    tags.py              the tag catalogue and slug minting
    drafts.py            PendingDraft rows (the multi-draft import batch)
    setup_flow.py        the first-run capture flow behind /setup
    rehearsal.py         the local rehearsal harness's data layer
    discovery_events.py  DiscoveredEvent rows (leads the sweep found)
    broadcast.py         the admin broadcast
    delivery.py          delivery_log and the per-tick digest
    calendar_feed.py     the personal .ics subscription
    translation_gaps.py  the edit pages' "what's missing" notice
    ops_alerts.py        health checks -> admin DMs
    phrases.py           the round-label phrase library
    quiet_ladders.py     the round-watch predicate and worklist query
    audit.py             ConcertAudit, the concert edit history
    venues.py            the legs -> concert VENUE tag rollup
    tokens.py            secret tokens at rest -- one hash implementation
                         shared by the calendar feed and the agent API token

WHY `core` is still 4,000 lines, and why that is not laziness: its nine
sections are MUTUALLY recursive -- measured, not assumed. Queue sync,
retrieval, the board, the concert page, Discover status, presets and the DM
actions form one strongly-connected component in the call graph, so no cut
through them yields modules that import in one direction. Splitting it needs
a real design change (see WISHLIST.md), not a file move, and doing it by
moving lines would buy smaller files at the price of import cycles.

Everything extracted here WAS acyclic: core references nothing in any of the
fourteen feature modules, which is what made this safe to do mechanically.

WHY a facade rather than importing the feature modules at the bottom of a
still-fat service.py: they import FROM core, so a bottom import would only
work while `app.db.service` happened to be imported first. `import
app.db.tags` on its own would then hit a half-initialised module and die.
A facade that imports from everything and is imported by nothing cannot have
that problem.

Adding a name to one of the modules above does NOT export it -- add it to the
matching import list here too. `test_service_facade.py` fails if the two
disagree, so this cannot silently rot.
"""

from app.db.audit import (
    TRACKED_CONCERT_FIELDS,
    _audit_value,
    concert_audit_log,
    record_concert_edit,
    snapshot_concert,
)
from app.db.broadcast import (
    _DUPLICATE_WINDOW,
    BROADCAST_BODY_MAX,
    HOLD_SECONDS,
    TYPED_CONFIRM_THRESHOLD,
    Recipients,
    _framed_body,
    cancel_broadcast,
    duplicate_body_recently,
    queue_broadcast,
    recent_broadcasts,
    resolve_recipients,
)
from app.db.calendar_feed import (
    CalendarEvent,
    generate_calendar_token,
    get_user_by_calendar_token,
    user_calendar_events,
)
from app.db.core import (
    _FOLD_KINDS,
    ANCHOR_FAN_OUT,
    DEADLINE_ROWS_LIMIT,
    LABEL_BY_ANCHOR,
    LABEL_BY_ROUND_KIND,
    VISIBLE_BLOCKS,
    BoardCard,
    ConcertBlock,
    DeadlineRow,
    DiscoverStatus,
    DueReminder,
    LegCancelledContext,
    LegRounds,
    NoticeContext,
    RoundRow,
    Rung,
    UpcomingDeadline,
    _api_concert_row,
    _apply_outcome_suppression,
    _auto_arm_next_round,
    _can_resolve_days,
    _concert_opted_out,
    _covered_day_ids,
    _covered_from_secured,
    _day_capture_context,
    _day_info,
    _day_month,
    _eligible_upgrade_ids,
    _first_leg_sort_key,
    _fold_counts,
    _humanize_until,
    _jst_date,
    _leg_result_for,
    _materialize_implicit_won_rows,
    _needs_you,
    _next_anchor_iso,
    _next_deadline,
    _next_moment_key,
    _next_round_for_leg,
    _now,
    _open_round_criterion,
    _primary_anchor,
    _qualifiers_by_upgrade_round,
    _result_moment,
    _round_fully_opted_out,
    _round_has_opened,
    _round_info,
    _round_is_open,
    _round_outcome_value,
    _rule_info,
    _rung_state,
    _secured_from_outcome_rows,
    _settle_lost_days,
    _split_leg_rounds,
    _wants_you,
    _won_day_ids,
    all_legs_cancelled,
    api_concert_detail,
    api_concert_rows,
    apply_default_preset,
    apply_preset,
    board_cards,
    capture_gates,
    catalogue_tag_counts,
    clear_concert_subscription,
    concert_next_moment,
    concert_round_rows,
    concert_search_text,
    concert_subscription_states,
    covered_round_ids,
    covered_round_ids_by_concert,
    create_preset_from_rules,
    delete_user,
    discover_peek,
    discover_statuses,
    discoverable_concert_count,
    discoverable_concert_criterion,
    discoverable_open_round_count,
    discoverable_tag_counts,
    due_notifications,
    due_reminders,
    ensure_user,
    followed_tag_counts,
    get_default_preset,
    handle_newly_tagged,
    has_day_results,
    is_round_cancelled,
    leg_cancelled_context,
    list_editors,
    mark_notification_sent,
    mark_sent,
    my_deadline_blocks,
    my_deadline_rows,
    my_upcoming_deadlines,
    next_anchor_at,
    notice_context,
    notify_newly_cancelled_legs,
    record_dm_outcome,
    record_remaining_days_lost,
    record_round_day_result,
    record_round_outcome,
    reinstate_user_rules,
    remove_user_rules,
    round_result_state,
    secured_day_ids_by_round,
    set_concert_subscription,
    set_default_preset,
    set_editor,
    set_leg_opt_out,
    snooze_reminder,
    sync_concert,
    sync_rule,
    tracked_concert_ids,
    unresolved_day_ids,
    upcoming_concert_count,
    upcoming_deadlines,
    upcoming_rounds,
    user_opted_out_day_ids,
)
from app.db.delivery import (
    DELIVERY_LOG_RETENTION_DAYS,
    UNREPORTED_NOTE_KINDS,
    BatchSummary,
    delivery_batch_rows,
    delivery_batches,
    delivery_failures,
    prune_delivery_log,
    queue_delivery_digest,
    record_deliveries,
)
from app.db.discovery_events import (
    DiscoveredInput,
    _bind_leads_to_concerts,
    api_lead_rows,
    dismiss_lead,
    dismissed_reason_counts,
    open_leads,
    record_discovered,
)
from app.db.drafts import (
    DISCOVERY_INTERVAL,
    DISCOVERY_STATE_ID,
    PlannedDismissal,
    PrunePlan,
    PruneReport,
    _phase_two_already_ran,
    api_draft_detail,
    api_draft_rows,
    apply_prune,
    approved_fetch_hosts,
    completion_candidates,
    create_pending_drafts,
    decide_fetch_domain,
    discard_pending_draft,
    discovery_due,
    discovery_status,
    fetch_domain_rows,
    get_triage_run,
    latest_triage_run,
    leads_matching_existing_legs,
    mark_leads_announced,
    mark_pending_committed,
    mark_triage_failed,
    note_fetch_domain,
    pending_draft_texts,
    pending_drafts,
    pending_fetch_domain_count,
    pending_triage_run,
    plan_prune,
    request_sweep,
    request_triage,
    set_sweep_cursor,
    stamp_discovery_run,
    sweep_requested,
)
from app.db.ops_alerts import (
    evaluate_and_alert,
)
from app.db.phrases import (
    forget_round_label_phrase,
    record_round_label_phrase,
    round_label_phrases,
)
from app.db.quiet_ladders import (
    QuietLadder,
    QuietRound,
    _all_concerts,
    _not_yet_performed,
    _quiet_concerts,
    _row,
    is_quiet,
    quiet_ladder_rows,
    reconcile_quiet_ladders,
    record_ladder_checked,
)
from app.db.rehearsal import (
    REHEARSAL_EVENT_ID,
    REHEARSAL_TAG_NAME,
    RehearsalRow,
    cancel_rehearsal_show,
    get_rehearsal_concert,
    pull_rehearsal_forward,
    rehearsal_queue_rows,
    rehearsal_rows,
    seed_rehearsal,
    teardown_rehearsal,
)
from app.db.setup_flow import (
    _BECAUSE_KIND_ORDER,
    SetupAskRow,
    SetupTallies,
    SetupTile,
    _next_round_anchor,
    _round_asks_application,
    _setup_tile_venue,
    _tracked_upcoming_concerts,
    apply_prune_selection,
    record_setup_applications,
    setup_application_rows,
    setup_prune_tiles,
    setup_tallies,
)
from app.db.tags import (
    _HANDLE_FIELDS,
    ImportChoices,
    PerformerCluster,
    PerformerEntry,
    TagCounts,
    TagImportReport,
    _detach_one,
    _is_attached,
    _takes_handle,
    active_concerts_missing_member,
    api_tag_rows,
    apply_tag_import,
    assign_tag_slug,
    attach_tag,
    catalogue_export_files,
    concert_export_yaml,
    create_tag_row,
    current_tag_exports,
    detach_tag,
    find_tags_by_name_and_kind,
    group_members,
    match_tag_ids_by_name,
    match_tag_ids_by_slug,
    match_venue_tag_id,
    match_venue_tag_id_by_slug,
    performer_clusters,
    resolve_group_member,
    tag_directory_context,
    tag_picker_context,
    would_create_tag_cycle,
)
from app.db.tokens import (
    generate_api_token,
    get_user_by_api_token,
    hash_token,
)
from app.db.translation_gaps import (
    VariantGap,
    _regroup_gaps,
    concert_variant_gaps,
    tag_variant_gaps,
)
from app.db.venues import (
    sync_concert_venue_tags,
)

__all__ = [
    "ANCHOR_FAN_OUT",
    "BROADCAST_BODY_MAX",
    "BatchSummary",
    "BoardCard",
    "CalendarEvent",
    "ConcertBlock",
    "DEADLINE_ROWS_LIMIT",
    "DELIVERY_LOG_RETENTION_DAYS",
    "DISCOVERY_INTERVAL",
    "DISCOVERY_STATE_ID",
    "DeadlineRow",
    "DiscoverStatus",
    "DiscoveredInput",
    "DueReminder",
    "HOLD_SECONDS",
    "ImportChoices",
    "LABEL_BY_ANCHOR",
    "LABEL_BY_ROUND_KIND",
    "LegCancelledContext",
    "LegRounds",
    "NoticeContext",
    "PerformerCluster",
    "PerformerEntry",
    "PlannedDismissal",
    "PrunePlan",
    "PruneReport",
    "QuietLadder",
    "QuietRound",
    "REHEARSAL_EVENT_ID",
    "REHEARSAL_TAG_NAME",
    "Recipients",
    "RehearsalRow",
    "RoundRow",
    "Rung",
    "SetupAskRow",
    "SetupTallies",
    "SetupTile",
    "TRACKED_CONCERT_FIELDS",
    "TYPED_CONFIRM_THRESHOLD",
    "TagCounts",
    "TagImportReport",
    "UNREPORTED_NOTE_KINDS",
    "UpcomingDeadline",
    "VISIBLE_BLOCKS",
    "VariantGap",
    "_BECAUSE_KIND_ORDER",
    "_DUPLICATE_WINDOW",
    "_FOLD_KINDS",
    "_HANDLE_FIELDS",
    "_all_concerts",
    "_api_concert_row",
    "_apply_outcome_suppression",
    "_audit_value",
    "_auto_arm_next_round",
    "_bind_leads_to_concerts",
    "_can_resolve_days",
    "_concert_opted_out",
    "_covered_day_ids",
    "_covered_from_secured",
    "_day_capture_context",
    "_day_info",
    "_day_month",
    "_detach_one",
    "_eligible_upgrade_ids",
    "_first_leg_sort_key",
    "_fold_counts",
    "_framed_body",
    "_humanize_until",
    "_is_attached",
    "_jst_date",
    "_leg_result_for",
    "_materialize_implicit_won_rows",
    "_needs_you",
    "_next_anchor_iso",
    "_next_deadline",
    "_next_moment_key",
    "_next_round_anchor",
    "_next_round_for_leg",
    "_not_yet_performed",
    "_now",
    "_open_round_criterion",
    "_phase_two_already_ran",
    "_primary_anchor",
    "_qualifiers_by_upgrade_round",
    "_quiet_concerts",
    "_regroup_gaps",
    "_result_moment",
    "_round_asks_application",
    "_round_fully_opted_out",
    "_round_has_opened",
    "_round_info",
    "_round_is_open",
    "_round_outcome_value",
    "_row",
    "_rule_info",
    "_rung_state",
    "_secured_from_outcome_rows",
    "_settle_lost_days",
    "_setup_tile_venue",
    "_split_leg_rounds",
    "_takes_handle",
    "_tracked_upcoming_concerts",
    "_wants_you",
    "_won_day_ids",
    "active_concerts_missing_member",
    "all_legs_cancelled",
    "api_concert_detail",
    "api_concert_rows",
    "api_draft_detail",
    "api_draft_rows",
    "api_lead_rows",
    "api_tag_rows",
    "apply_default_preset",
    "apply_preset",
    "apply_prune",
    "apply_prune_selection",
    "apply_tag_import",
    "approved_fetch_hosts",
    "assign_tag_slug",
    "attach_tag",
    "board_cards",
    "cancel_broadcast",
    "cancel_rehearsal_show",
    "capture_gates",
    "catalogue_export_files",
    "catalogue_tag_counts",
    "clear_concert_subscription",
    "completion_candidates",
    "concert_audit_log",
    "concert_export_yaml",
    "concert_next_moment",
    "concert_round_rows",
    "concert_search_text",
    "concert_subscription_states",
    "concert_variant_gaps",
    "covered_round_ids",
    "covered_round_ids_by_concert",
    "create_pending_drafts",
    "create_preset_from_rules",
    "create_tag_row",
    "current_tag_exports",
    "decide_fetch_domain",
    "delete_user",
    "delivery_batch_rows",
    "delivery_batches",
    "delivery_failures",
    "detach_tag",
    "discard_pending_draft",
    "discover_peek",
    "discover_statuses",
    "discoverable_concert_count",
    "discoverable_concert_criterion",
    "discoverable_open_round_count",
    "discoverable_tag_counts",
    "discovery_due",
    "discovery_status",
    "dismiss_lead",
    "dismissed_reason_counts",
    "due_notifications",
    "due_reminders",
    "duplicate_body_recently",
    "ensure_user",
    "evaluate_and_alert",
    "fetch_domain_rows",
    "find_tags_by_name_and_kind",
    "followed_tag_counts",
    "forget_round_label_phrase",
    "generate_api_token",
    "generate_calendar_token",
    "get_default_preset",
    "get_rehearsal_concert",
    "get_triage_run",
    "get_user_by_api_token",
    "get_user_by_calendar_token",
    "group_members",
    "handle_newly_tagged",
    "has_day_results",
    "hash_token",
    "is_quiet",
    "is_round_cancelled",
    "latest_triage_run",
    "leads_matching_existing_legs",
    "leg_cancelled_context",
    "list_editors",
    "mark_leads_announced",
    "mark_notification_sent",
    "mark_pending_committed",
    "mark_sent",
    "mark_triage_failed",
    "match_tag_ids_by_name",
    "match_tag_ids_by_slug",
    "match_venue_tag_id",
    "match_venue_tag_id_by_slug",
    "my_deadline_blocks",
    "my_deadline_rows",
    "my_upcoming_deadlines",
    "next_anchor_at",
    "note_fetch_domain",
    "notice_context",
    "notify_newly_cancelled_legs",
    "open_leads",
    "pending_draft_texts",
    "pending_drafts",
    "pending_fetch_domain_count",
    "pending_triage_run",
    "performer_clusters",
    "plan_prune",
    "prune_delivery_log",
    "pull_rehearsal_forward",
    "queue_broadcast",
    "queue_delivery_digest",
    "quiet_ladder_rows",
    "recent_broadcasts",
    "reconcile_quiet_ladders",
    "record_concert_edit",
    "record_deliveries",
    "record_discovered",
    "record_dm_outcome",
    "record_ladder_checked",
    "record_remaining_days_lost",
    "record_round_day_result",
    "record_round_label_phrase",
    "record_round_outcome",
    "record_setup_applications",
    "rehearsal_queue_rows",
    "rehearsal_rows",
    "reinstate_user_rules",
    "remove_user_rules",
    "request_sweep",
    "request_triage",
    "resolve_group_member",
    "resolve_recipients",
    "round_label_phrases",
    "round_result_state",
    "secured_day_ids_by_round",
    "seed_rehearsal",
    "set_concert_subscription",
    "set_default_preset",
    "set_editor",
    "set_leg_opt_out",
    "set_sweep_cursor",
    "setup_application_rows",
    "setup_prune_tiles",
    "setup_tallies",
    "snapshot_concert",
    "snooze_reminder",
    "stamp_discovery_run",
    "sweep_requested",
    "sync_concert",
    "sync_concert_venue_tags",
    "sync_rule",
    "tag_directory_context",
    "tag_picker_context",
    "tag_variant_gaps",
    "teardown_rehearsal",
    "tracked_concert_ids",
    "unresolved_day_ids",
    "upcoming_concert_count",
    "upcoming_deadlines",
    "upcoming_rounds",
    "user_calendar_events",
    "user_opted_out_day_ids",
    "would_create_tag_cycle",
]
